apiVersion: compute.exoscale.exoscale.ch/v1alpha1
kind: SecurityGroupRules
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/securitygrouprules
  labels:
    testing.upbound.io/example-name: my_security_group_rule
  name: my-security-group-rule
spec:
  forProvider:
    cidr: 0.0.0.0/0
    endPort: 80
    protocol: TCP
    securityGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: my_security_group
    startPort: 80
    type: INGRESS

---

apiVersion: compute.exoscale.exoscale.ch/v1alpha1
kind: SecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/securitygrouprules
  labels:
    testing.upbound.io/example-name: my_security_group
  name: my-security-group
spec:
  forProvider:
    name: my-security-group
