apiVersion: compute.exoscale.m.exoscale.ch/v1alpha1
kind: AntiAffinityGroup
metadata:
  name: my-anti-affinity-group
  namespace: crossplane-system
spec:
  forProvider:
    description: Prevent compute instances to run on the same host
    name: my-anti-affinity-group
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default
