apiVersion: compute.exoscale.m.exoscale.ch/v1alpha1
kind: ElasticIP
metadata:
  name: my-elastic-ip
  namespace: crossplane-system
spec:
  forProvider:
    zone: ch-gva-2
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default
