// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type IAMRoleInitParameters struct {

	// A free-form text describing the IAM Role
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Defines if IAM Role Policy is editable or not.
	Editable *bool `json:"editable,omitempty" tf:"editable,omitempty"`

	// IAM Role labels.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// ❗Name of IAM Role.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// IAM Role permissions.
	Permissions []*string `json:"permissions,omitempty" tf:"permissions,omitempty"`

	Policy *PolicyInitParameters `json:"policy,omitempty" tf:"policy,omitempty"`
}

type IAMRoleObservation struct {

	// A free-form text describing the IAM Role
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Defines if IAM Role Policy is editable or not.
	Editable *bool `json:"editable,omitempty" tf:"editable,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// IAM Role labels.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// ❗Name of IAM Role.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// IAM Role permissions.
	Permissions []*string `json:"permissions,omitempty" tf:"permissions,omitempty"`

	Policy *PolicyObservation `json:"policy,omitempty" tf:"policy,omitempty"`
}

type IAMRoleParameters struct {

	// A free-form text describing the IAM Role
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Defines if IAM Role Policy is editable or not.
	// +kubebuilder:validation:Optional
	Editable *bool `json:"editable,omitempty" tf:"editable,omitempty"`

	// IAM Role labels.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// ❗Name of IAM Role.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// IAM Role permissions.
	// +kubebuilder:validation:Optional
	Permissions []*string `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// +kubebuilder:validation:Optional
	Policy *PolicyParameters `json:"policy,omitempty" tf:"policy,omitempty"`
}

type PolicyInitParameters struct {

	// Default service strategy (`allow` or `deny`).
	DefaultServiceStrategy *string `json:"defaultServiceStrategy,omitempty" tf:"default_service_strategy,omitempty"`

	Services map[string]ServicesInitParameters `json:"services,omitempty" tf:"services,omitempty"`
}

type PolicyObservation struct {

	// Default service strategy (`allow` or `deny`).
	DefaultServiceStrategy *string `json:"defaultServiceStrategy,omitempty" tf:"default_service_strategy,omitempty"`

	Services map[string]ServicesObservation `json:"services,omitempty" tf:"services,omitempty"`
}

type PolicyParameters struct {

	// Default service strategy (`allow` or `deny`).
	// +kubebuilder:validation:Optional
	DefaultServiceStrategy *string `json:"defaultServiceStrategy,omitempty" tf:"default_service_strategy,omitempty"`

	// +kubebuilder:validation:Optional
	Services map[string]ServicesParameters `json:"services,omitempty" tf:"services,omitempty"`
}

type RulesInitParameters struct {

	// IAM policy rule action (`allow` or `deny`).
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// IAM policy rule expression.
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	Resources []*string `json:"resources,omitempty" tf:"resources,omitempty"`
}

type RulesObservation struct {

	// IAM policy rule action (`allow` or `deny`).
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// IAM policy rule expression.
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	Resources []*string `json:"resources,omitempty" tf:"resources,omitempty"`
}

type RulesParameters struct {

	// IAM policy rule action (`allow` or `deny`).
	// +kubebuilder:validation:Optional
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// IAM policy rule expression.
	// +kubebuilder:validation:Optional
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	// +kubebuilder:validation:Optional
	Resources []*string `json:"resources,omitempty" tf:"resources,omitempty"`
}

type ServicesInitParameters struct {
	Rules []RulesInitParameters `json:"rules,omitempty" tf:"rules,omitempty"`

	// Service type (`rules`, `allow`, or `deny`).
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ServicesObservation struct {
	Rules []RulesObservation `json:"rules,omitempty" tf:"rules,omitempty"`

	// Service type (`rules`, `allow`, or `deny`).
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ServicesParameters struct {

	// +kubebuilder:validation:Optional
	Rules []RulesParameters `json:"rules,omitempty" tf:"rules,omitempty"`

	// Service type (`rules`, `allow`, or `deny`).
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// IAMRoleSpec defines the desired state of IAMRole
type IAMRoleSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            IAMRoleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider IAMRoleInitParameters `json:"initProvider,omitempty"`
}

// IAMRoleStatus defines the observed state of IAMRole.
type IAMRoleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        IAMRoleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// IAMRole is the Schema for the IAMRoles API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,exoscale}
type IAMRole struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   IAMRoleSpec   `json:"spec"`
	Status IAMRoleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// IAMRoleList contains a list of IAMRoles
type IAMRoleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []IAMRole `json:"items"`
}

// Repository type metadata.
var (
	IAMRole_Kind             = "IAMRole"
	IAMRole_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: IAMRole_Kind}.String()
	IAMRole_KindAPIVersion   = IAMRole_Kind + "." + CRDGroupVersion.String()
	IAMRole_GroupVersionKind = CRDGroupVersion.WithKind(IAMRole_Kind)
)

func init() {
	SchemeBuilder.Register(&IAMRole{}, &IAMRoleList{})
}
