// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type IAMOrgPolicyInitParameters struct {

	// (String) Default service strategy (allow or deny).
	// Default service strategy (`allow` or `deny`).
	DefaultServiceStrategy *string `json:"defaultServiceStrategy,omitempty" tf:"default_service_strategy,omitempty"`

	// (Attributes Map) IAM policy services. (see below for nested schema)
	Services map[string]ServicesInitParameters `json:"services,omitempty" tf:"services,omitempty"`
}

type IAMOrgPolicyObservation struct {

	// (String) Default service strategy (allow or deny).
	// Default service strategy (`allow` or `deny`).
	DefaultServiceStrategy *string `json:"defaultServiceStrategy,omitempty" tf:"default_service_strategy,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Attributes Map) IAM policy services. (see below for nested schema)
	Services map[string]ServicesObservation `json:"services,omitempty" tf:"services,omitempty"`
}

type IAMOrgPolicyParameters struct {

	// (String) Default service strategy (allow or deny).
	// Default service strategy (`allow` or `deny`).
	// +kubebuilder:validation:Optional
	DefaultServiceStrategy *string `json:"defaultServiceStrategy,omitempty" tf:"default_service_strategy,omitempty"`

	// (Attributes Map) IAM policy services. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Services map[string]ServicesParameters `json:"services,omitempty" tf:"services,omitempty"`
}

type RulesInitParameters struct {

	// (String) IAM policy rule action (allow or deny).
	// IAM policy rule action (`allow` or `deny`).
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// (String) IAM policy rule expression.
	// IAM policy rule expression.
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	// (List of String, Deprecated)
	Resources []*string `json:"resources,omitempty" tf:"resources,omitempty"`
}

type RulesObservation struct {

	// (String) IAM policy rule action (allow or deny).
	// IAM policy rule action (`allow` or `deny`).
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// (String) IAM policy rule expression.
	// IAM policy rule expression.
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	// (List of String, Deprecated)
	Resources []*string `json:"resources,omitempty" tf:"resources,omitempty"`
}

type RulesParameters struct {

	// (String) IAM policy rule action (allow or deny).
	// IAM policy rule action (`allow` or `deny`).
	// +kubebuilder:validation:Optional
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// (String) IAM policy rule expression.
	// IAM policy rule expression.
	// +kubebuilder:validation:Optional
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	// (List of String, Deprecated)
	// +kubebuilder:validation:Optional
	Resources []*string `json:"resources,omitempty" tf:"resources,omitempty"`
}

type ServicesInitParameters struct {

	// (Attributes List) List of IAM service rules (if type is rules). (see below for nested schema)
	Rules []RulesInitParameters `json:"rules,omitempty" tf:"rules,omitempty"`

	// (String) Service type (rules, allow, or deny).
	// Service type (`rules`, `allow`, or `deny`).
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ServicesObservation struct {

	// (Attributes List) List of IAM service rules (if type is rules). (see below for nested schema)
	Rules []RulesObservation `json:"rules,omitempty" tf:"rules,omitempty"`

	// (String) Service type (rules, allow, or deny).
	// Service type (`rules`, `allow`, or `deny`).
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ServicesParameters struct {

	// (Attributes List) List of IAM service rules (if type is rules). (see below for nested schema)
	// +kubebuilder:validation:Optional
	Rules []RulesParameters `json:"rules,omitempty" tf:"rules,omitempty"`

	// (String) Service type (rules, allow, or deny).
	// Service type (`rules`, `allow`, or `deny`).
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// IAMOrgPolicySpec defines the desired state of IAMOrgPolicy
type IAMOrgPolicySpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            IAMOrgPolicyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider IAMOrgPolicyInitParameters `json:"initProvider,omitempty"`
}

// IAMOrgPolicyStatus defines the observed state of IAMOrgPolicy.
type IAMOrgPolicyStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        IAMOrgPolicyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// IAMOrgPolicy is the Schema for the IAMOrgPolicys API. Manage Exoscale IAM Org Policy
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,exoscale}
type IAMOrgPolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.defaultServiceStrategy) || (has(self.initProvider) && has(self.initProvider.defaultServiceStrategy))",message="spec.forProvider.defaultServiceStrategy is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.services) || (has(self.initProvider) && has(self.initProvider.services))",message="spec.forProvider.services is a required parameter"
	Spec   IAMOrgPolicySpec   `json:"spec"`
	Status IAMOrgPolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// IAMOrgPolicyList contains a list of IAMOrgPolicys
type IAMOrgPolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []IAMOrgPolicy `json:"items"`
}

// Repository type metadata.
var (
	IAMOrgPolicy_Kind             = "IAMOrgPolicy"
	IAMOrgPolicy_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: IAMOrgPolicy_Kind}.String()
	IAMOrgPolicy_KindAPIVersion   = IAMOrgPolicy_Kind + "." + CRDGroupVersion.String()
	IAMOrgPolicy_GroupVersionKind = CRDGroupVersion.WithKind(IAMOrgPolicy_Kind)
)

func init() {
	SchemeBuilder.Register(&IAMOrgPolicy{}, &IAMOrgPolicyList{})
}
