// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type AntiAffinityGroupInitParameters struct {

	// form text describing the group.
	// ❗ A free-form text describing the group.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// affinity group name.
	// ❗ The anti-affinity group name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type AntiAffinityGroupObservation struct {

	// form text describing the group.
	// ❗ A free-form text describing the group.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// affinity group name.
	// ❗ The anti-affinity group name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type AntiAffinityGroupParameters struct {

	// form text describing the group.
	// ❗ A free-form text describing the group.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// affinity group name.
	// ❗ The anti-affinity group name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// AntiAffinityGroupSpec defines the desired state of AntiAffinityGroup
type AntiAffinityGroupSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            AntiAffinityGroupParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AntiAffinityGroupInitParameters `json:"initProvider,omitempty"`
}

// AntiAffinityGroupStatus defines the observed state of AntiAffinityGroup.
type AntiAffinityGroupStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AntiAffinityGroupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AntiAffinityGroup is the Schema for the AntiAffinityGroups API. Manage Exoscale Anti-Affinity Groups https://community.exoscale.com/product/compute/instances/how-to/anti-affinity/. Corresponding data source: exoscaleantiaffinity_group ../data-sources/anti_affinity_group.md.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,exoscale}
type AntiAffinityGroup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   AntiAffinityGroupSpec   `json:"spec"`
	Status AntiAffinityGroupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AntiAffinityGroupList contains a list of AntiAffinityGroups
type AntiAffinityGroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AntiAffinityGroup `json:"items"`
}

// Repository type metadata.
var (
	AntiAffinityGroup_Kind             = "AntiAffinityGroup"
	AntiAffinityGroup_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AntiAffinityGroup_Kind}.String()
	AntiAffinityGroup_KindAPIVersion   = AntiAffinityGroup_Kind + "." + CRDGroupVersion.String()
	AntiAffinityGroup_GroupVersionKind = CRDGroupVersion.WithKind(AntiAffinityGroup_Kind)
)

func init() {
	SchemeBuilder.Register(&AntiAffinityGroup{}, &AntiAffinityGroupList{})
}
