// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ElasticIPInitParameters struct {

	// (String) ❗ The Elastic IP (EIP) address family (inet4 or inet6; default: inet4).
	// ❗ The Elastic IP (EIP) address family (`inet4` or `inet6`; default: `inet4`).
	AddressFamily *string `json:"addressFamily,omitempty" tf:"address_family,omitempty"`

	// form text describing the Elastic IP (EIP).
	// A free-form text describing the Elastic IP (EIP).
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Block List, Max: 1) Healthcheck configuration for managed EIPs. It can not be added to an existing Unmanaged EIP. (see below for nested schema)
	// Healthcheck configuration for *managed* EIPs. It can not be added to an existing *Unmanaged* EIP.
	Healthcheck []HealthcheckInitParameters `json:"healthcheck,omitempty" tf:"healthcheck,omitempty"`

	// (Map of String) A map of key/value labels.
	// A map of key/value labels.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) Domain name for reverse DNS record.
	// Domain name for reverse DNS record.
	ReverseDNS *string `json:"reverseDns,omitempty" tf:"reverse_dns,omitempty"`

	// (String) ❗ The Exoscale Zone name.
	// ❗ The Exoscale [Zone](https://www.exoscale.com/datacenters/) name.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type ElasticIPObservation struct {

	// (String) ❗ The Elastic IP (EIP) address family (inet4 or inet6; default: inet4).
	// ❗ The Elastic IP (EIP) address family (`inet4` or `inet6`; default: `inet4`).
	AddressFamily *string `json:"addressFamily,omitempty" tf:"address_family,omitempty"`

	// (String) The Elastic IP (EIP) CIDR.
	// The Elastic IP (EIP) CIDR.
	Cidr *string `json:"cidr,omitempty" tf:"cidr,omitempty"`

	// form text describing the Elastic IP (EIP).
	// A free-form text describing the Elastic IP (EIP).
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Block List, Max: 1) Healthcheck configuration for managed EIPs. It can not be added to an existing Unmanaged EIP. (see below for nested schema)
	// Healthcheck configuration for *managed* EIPs. It can not be added to an existing *Unmanaged* EIP.
	Healthcheck []HealthcheckObservation `json:"healthcheck,omitempty" tf:"healthcheck,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The Elastic IP (EIP) IPv4 or IPv6 address.
	// The Elastic IP (EIP) IPv4 or IPv6 address.
	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`

	// (Map of String) A map of key/value labels.
	// A map of key/value labels.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) Domain name for reverse DNS record.
	// Domain name for reverse DNS record.
	ReverseDNS *string `json:"reverseDns,omitempty" tf:"reverse_dns,omitempty"`

	// (String) ❗ The Exoscale Zone name.
	// ❗ The Exoscale [Zone](https://www.exoscale.com/datacenters/) name.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type ElasticIPParameters struct {

	// (String) ❗ The Elastic IP (EIP) address family (inet4 or inet6; default: inet4).
	// ❗ The Elastic IP (EIP) address family (`inet4` or `inet6`; default: `inet4`).
	// +kubebuilder:validation:Optional
	AddressFamily *string `json:"addressFamily,omitempty" tf:"address_family,omitempty"`

	// form text describing the Elastic IP (EIP).
	// A free-form text describing the Elastic IP (EIP).
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Block List, Max: 1) Healthcheck configuration for managed EIPs. It can not be added to an existing Unmanaged EIP. (see below for nested schema)
	// Healthcheck configuration for *managed* EIPs. It can not be added to an existing *Unmanaged* EIP.
	// +kubebuilder:validation:Optional
	Healthcheck []HealthcheckParameters `json:"healthcheck,omitempty" tf:"healthcheck,omitempty"`

	// (Map of String) A map of key/value labels.
	// A map of key/value labels.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) Domain name for reverse DNS record.
	// Domain name for reverse DNS record.
	// +kubebuilder:validation:Optional
	ReverseDNS *string `json:"reverseDns,omitempty" tf:"reverse_dns,omitempty"`

	// (String) ❗ The Exoscale Zone name.
	// ❗ The Exoscale [Zone](https://www.exoscale.com/datacenters/) name.
	// +kubebuilder:validation:Optional
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type HealthcheckInitParameters struct {

	// (Number) The healthcheck interval (seconds; must be between 5 and 300; default: 10).
	// The healthcheck interval (seconds; must be between `5` and `300`; default: `10`).
	Interval *float64 `json:"interval,omitempty" tf:"interval,omitempty"`

	// (String) The healthcheck mode (tcp, http or https; may only be set at creation time).
	// The healthcheck mode (`tcp`, `http` or `https`; may only be set at creation time).
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// (Number) The healthcheck target port (must be between 1 and 65535).
	// The healthcheck target port (must be between `1` and `65535`).
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// (Number) The number of failed healthcheck attempts before considering the target unhealthy (must be between 1 and 20; default: 2).
	// The number of failed healthcheck attempts before considering the target unhealthy (must be between `1` and `20`; default: `2`).
	StrikesFail *float64 `json:"strikesFail,omitempty" tf:"strikes_fail,omitempty"`

	// (Number) The number of successful healthcheck attempts before considering the target healthy (must be between 1 and 20; default: 3).
	// The number of successful healthcheck attempts before considering the target healthy (must be between `1` and `20`; default: `3`).
	StrikesOk *float64 `json:"strikesOk,omitempty" tf:"strikes_ok,omitempty"`

	// (Boolean) Disable TLS certificate verification for healthcheck in https mode (boolean; default: false).
	// Disable TLS certificate verification for healthcheck in `https` mode (boolean; default: `false`).
	TLSSkipVerify *bool `json:"tlsSkipVerify,omitempty" tf:"tls_skip_verify,omitempty"`

	// (String) The healthcheck server name to present with SNI in https mode.
	// The healthcheck server name to present with SNI in `https` mode.
	TLSSni *string `json:"tlsSni,omitempty" tf:"tls_sni,omitempty"`

	// (Number) The time before considering a healthcheck probing failed (seconds; must be between 2 and 60; default: 3).
	// The time before considering a healthcheck probing failed (seconds; must be between `2` and `60`; default: `3`).
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// (String) The healthcheck target URI  modes).
	// The healthcheck target URI (required in `http(s)` modes).
	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`
}

type HealthcheckObservation struct {

	// (Number) The healthcheck interval (seconds; must be between 5 and 300; default: 10).
	// The healthcheck interval (seconds; must be between `5` and `300`; default: `10`).
	Interval *float64 `json:"interval,omitempty" tf:"interval,omitempty"`

	// (String) The healthcheck mode (tcp, http or https; may only be set at creation time).
	// The healthcheck mode (`tcp`, `http` or `https`; may only be set at creation time).
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// (Number) The healthcheck target port (must be between 1 and 65535).
	// The healthcheck target port (must be between `1` and `65535`).
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// (Number) The number of failed healthcheck attempts before considering the target unhealthy (must be between 1 and 20; default: 2).
	// The number of failed healthcheck attempts before considering the target unhealthy (must be between `1` and `20`; default: `2`).
	StrikesFail *float64 `json:"strikesFail,omitempty" tf:"strikes_fail,omitempty"`

	// (Number) The number of successful healthcheck attempts before considering the target healthy (must be between 1 and 20; default: 3).
	// The number of successful healthcheck attempts before considering the target healthy (must be between `1` and `20`; default: `3`).
	StrikesOk *float64 `json:"strikesOk,omitempty" tf:"strikes_ok,omitempty"`

	// (Boolean) Disable TLS certificate verification for healthcheck in https mode (boolean; default: false).
	// Disable TLS certificate verification for healthcheck in `https` mode (boolean; default: `false`).
	TLSSkipVerify *bool `json:"tlsSkipVerify,omitempty" tf:"tls_skip_verify,omitempty"`

	// (String) The healthcheck server name to present with SNI in https mode.
	// The healthcheck server name to present with SNI in `https` mode.
	TLSSni *string `json:"tlsSni,omitempty" tf:"tls_sni,omitempty"`

	// (Number) The time before considering a healthcheck probing failed (seconds; must be between 2 and 60; default: 3).
	// The time before considering a healthcheck probing failed (seconds; must be between `2` and `60`; default: `3`).
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// (String) The healthcheck target URI  modes).
	// The healthcheck target URI (required in `http(s)` modes).
	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`
}

type HealthcheckParameters struct {

	// (Number) The healthcheck interval (seconds; must be between 5 and 300; default: 10).
	// The healthcheck interval (seconds; must be between `5` and `300`; default: `10`).
	// +kubebuilder:validation:Optional
	Interval *float64 `json:"interval,omitempty" tf:"interval,omitempty"`

	// (String) The healthcheck mode (tcp, http or https; may only be set at creation time).
	// The healthcheck mode (`tcp`, `http` or `https`; may only be set at creation time).
	// +kubebuilder:validation:Optional
	Mode *string `json:"mode" tf:"mode,omitempty"`

	// (Number) The healthcheck target port (must be between 1 and 65535).
	// The healthcheck target port (must be between `1` and `65535`).
	// +kubebuilder:validation:Optional
	Port *float64 `json:"port" tf:"port,omitempty"`

	// (Number) The number of failed healthcheck attempts before considering the target unhealthy (must be between 1 and 20; default: 2).
	// The number of failed healthcheck attempts before considering the target unhealthy (must be between `1` and `20`; default: `2`).
	// +kubebuilder:validation:Optional
	StrikesFail *float64 `json:"strikesFail,omitempty" tf:"strikes_fail,omitempty"`

	// (Number) The number of successful healthcheck attempts before considering the target healthy (must be between 1 and 20; default: 3).
	// The number of successful healthcheck attempts before considering the target healthy (must be between `1` and `20`; default: `3`).
	// +kubebuilder:validation:Optional
	StrikesOk *float64 `json:"strikesOk,omitempty" tf:"strikes_ok,omitempty"`

	// (Boolean) Disable TLS certificate verification for healthcheck in https mode (boolean; default: false).
	// Disable TLS certificate verification for healthcheck in `https` mode (boolean; default: `false`).
	// +kubebuilder:validation:Optional
	TLSSkipVerify *bool `json:"tlsSkipVerify,omitempty" tf:"tls_skip_verify,omitempty"`

	// (String) The healthcheck server name to present with SNI in https mode.
	// The healthcheck server name to present with SNI in `https` mode.
	// +kubebuilder:validation:Optional
	TLSSni *string `json:"tlsSni,omitempty" tf:"tls_sni,omitempty"`

	// (Number) The time before considering a healthcheck probing failed (seconds; must be between 2 and 60; default: 3).
	// The time before considering a healthcheck probing failed (seconds; must be between `2` and `60`; default: `3`).
	// +kubebuilder:validation:Optional
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// (String) The healthcheck target URI  modes).
	// The healthcheck target URI (required in `http(s)` modes).
	// +kubebuilder:validation:Optional
	URI *string `json:"uri,omitempty" tf:"uri,omitempty"`
}

// ElasticIPSpec defines the desired state of ElasticIP
type ElasticIPSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ElasticIPParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ElasticIPInitParameters `json:"initProvider,omitempty"`
}

// ElasticIPStatus defines the observed state of ElasticIP.
type ElasticIPStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ElasticIPObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ElasticIP is the Schema for the ElasticIPs API. Manage Exoscale Elastic IPs (EIP).
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,exoscale}
type ElasticIP struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.zone) || (has(self.initProvider) && has(self.initProvider.zone))",message="spec.forProvider.zone is a required parameter"
	Spec   ElasticIPSpec   `json:"spec"`
	Status ElasticIPStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ElasticIPList contains a list of ElasticIPs
type ElasticIPList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ElasticIP `json:"items"`
}

// Repository type metadata.
var (
	ElasticIP_Kind             = "ElasticIP"
	ElasticIP_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ElasticIP_Kind}.String()
	ElasticIP_KindAPIVersion   = ElasticIP_Kind + "." + CRDGroupVersion.String()
	ElasticIP_GroupVersionKind = CRDGroupVersion.WithKind(ElasticIP_Kind)
)

func init() {
	SchemeBuilder.Register(&ElasticIP{}, &ElasticIPList{})
}
