// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type InstancePoolInitParameters struct {

	// (Set of String, Deprecated) A list of exoscale_anti_affinity_group (IDs; may only be set at creation time).
	// A list of [exoscale_anti_affinity_group](./anti_affinity_group.md) (IDs; may only be set at creation time).
	// +crossplane:generate:reference:type=github.com/exoscale/provider-exoscale/apis/namespaced/compute/v1alpha1.AntiAffinityGroup
	// +listType=set
	AffinityGroupIds []*string `json:"affinityGroupIds,omitempty" tf:"affinity_group_ids,omitempty"`

	// References to AntiAffinityGroup in compute to populate affinityGroupIds.
	// +kubebuilder:validation:Optional
	AffinityGroupIdsRefs []v1.NamespacedReference `json:"affinityGroupIdsRefs,omitempty" tf:"-"`

	// Selector for a list of AntiAffinityGroup in compute to populate affinityGroupIds.
	// +kubebuilder:validation:Optional
	AffinityGroupIdsSelector *v1.NamespacedSelector `json:"affinityGroupIdsSelector,omitempty" tf:"-"`

	// (Set of String) A list of exoscale_anti_affinity_group (IDs; may only be set at creation time).
	// A list of [exoscale_anti_affinity_group](./anti_affinity_group.md) (IDs; may only be set at creation time).
	// +crossplane:generate:reference:type=github.com/exoscale/provider-exoscale/apis/namespaced/compute/v1alpha1.AntiAffinityGroup
	// +listType=set
	AntiAffinityGroupIds []*string `json:"antiAffinityGroupIds,omitempty" tf:"anti_affinity_group_ids,omitempty"`

	// References to AntiAffinityGroup in compute to populate antiAffinityGroupIds.
	// +kubebuilder:validation:Optional
	AntiAffinityGroupIdsRefs []v1.NamespacedReference `json:"antiAffinityGroupIdsRefs,omitempty" tf:"-"`

	// Selector for a list of AntiAffinityGroup in compute to populate antiAffinityGroupIds.
	// +kubebuilder:validation:Optional
	AntiAffinityGroupIdsSelector *v1.NamespacedSelector `json:"antiAffinityGroupIdsSelector,omitempty" tf:"-"`

	// (String) A deploy target ID.
	// A deploy target ID.
	DeployTargetID *string `json:"deployTargetId,omitempty" tf:"deploy_target_id,omitempty"`

	// form text describing the pool.
	// A free-form text describing the pool.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Number) The managed instances disk size (GiB).
	// The managed instances disk size (GiB).
	DiskSize *float64 `json:"diskSize,omitempty" tf:"disk_size,omitempty"`

	// (Set of String) A list of exoscale_elastic_ip (IDs).
	// A list of [exoscale_elastic_ip](./elastic_ip.md) (IDs).
	// +crossplane:generate:reference:type=github.com/exoscale/provider-exoscale/apis/namespaced/compute/v1alpha1.ElasticIP
	// +listType=set
	ElasticIPIds []*string `json:"elasticIpIds,omitempty" tf:"elastic_ip_ids,omitempty"`

	// References to ElasticIP in compute to populate elasticIpIds.
	// +kubebuilder:validation:Optional
	ElasticIPIdsRefs []v1.NamespacedReference `json:"elasticIpIdsRefs,omitempty" tf:"-"`

	// Selector for a list of ElasticIP in compute to populate elasticIpIds.
	// +kubebuilder:validation:Optional
	ElasticIPIdsSelector *v1.NamespacedSelector `json:"elasticIpIdsSelector,omitempty" tf:"-"`

	// (Boolean) Enable IPv6 on managed instances (boolean; default: false).
	// Enable IPv6 on managed instances (boolean; default: `false`).
	IPv6 *bool `json:"ipv6,omitempty" tf:"ipv6,omitempty"`

	// (String) The string used to prefix managed instances name (default: pool).
	// The string used to prefix managed instances name (default: `pool`).
	InstancePrefix *string `json:"instancePrefix,omitempty" tf:"instance_prefix,omitempty"`

	// exo compute instance-type list - for the list of available types).
	// The managed compute instances type (`<family>.<size>`, e.g. `standard.medium`; use the [Exoscale CLI](https://github.com/exoscale/cli/) - `exo compute instance-type list` - for the list of available types).
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// (Block Set) The list of managed instances. Structure is documented below. (see below for nested schema)
	// The list of managed instances. Structure is documented below.
	Instances []InstancesInitParameters `json:"instances,omitempty" tf:"instances,omitempty"`

	// (String) The exoscale_ssh_key (name) to authorize in the managed instances.
	// The [exoscale_ssh_key](./ssh_key.md) (name) to authorize in the managed instances.
	// +crossplane:generate:reference:type=github.com/exoscale/provider-exoscale/apis/namespaced/compute/v1alpha1.SSHKey
	KeyPair *string `json:"keyPair,omitempty" tf:"key_pair,omitempty"`

	// Reference to a SSHKey in compute to populate keyPair.
	// +kubebuilder:validation:Optional
	KeyPairRef *v1.NamespacedReference `json:"keyPairRef,omitempty" tf:"-"`

	// Selector for a SSHKey in compute to populate keyPair.
	// +kubebuilder:validation:Optional
	KeyPairSelector *v1.NamespacedSelector `json:"keyPairSelector,omitempty" tf:"-"`

	// (Map of String) A map of key/value labels.
	// A map of key/value labels.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (Number) Minimum number of running Instances.
	// Minimum number of running Instances.
	MinAvailable *float64 `json:"minAvailable,omitempty" tf:"min_available,omitempty"`

	// (String) The instance pool name.
	// The instance pool name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Set of String) A list of exoscale_private_network (IDs).
	// A list of [exoscale_private_network](./private_network.md) (IDs).
	// +crossplane:generate:reference:type=github.com/exoscale/provider-exoscale/apis/namespaced/compute/v1alpha1.PrivateNetwork
	// +listType=set
	NetworkIds []*string `json:"networkIds,omitempty" tf:"network_ids,omitempty"`

	// References to PrivateNetwork in compute to populate networkIds.
	// +kubebuilder:validation:Optional
	NetworkIdsRefs []v1.NamespacedReference `json:"networkIdsRefs,omitempty" tf:"-"`

	// Selector for a list of PrivateNetwork in compute to populate networkIds.
	// +kubebuilder:validation:Optional
	NetworkIdsSelector *v1.NamespacedSelector `json:"networkIdsSelector,omitempty" tf:"-"`

	// (Set of String) A list of exoscale_security_group (IDs).
	// A list of [exoscale_security_group](./security_group.md) (IDs).
	// +crossplane:generate:reference:type=github.com/exoscale/provider-exoscale/apis/namespaced/compute/v1alpha1.SecurityGroup
	// +listType=set
	SecurityGroupIds []*string `json:"securityGroupIds,omitempty" tf:"security_group_ids,omitempty"`

	// References to SecurityGroup in compute to populate securityGroupIds.
	// +kubebuilder:validation:Optional
	SecurityGroupIdsRefs []v1.NamespacedReference `json:"securityGroupIdsRefs,omitempty" tf:"-"`

	// Selector for a list of SecurityGroup in compute to populate securityGroupIds.
	// +kubebuilder:validation:Optional
	SecurityGroupIdsSelector *v1.NamespacedSelector `json:"securityGroupIdsSelector,omitempty" tf:"-"`

	// (String, Deprecated) The managed instances type. Please use the instance_type argument instead.
	// The managed instances type. Please use the `instance_type` argument instead.
	ServiceOffering *string `json:"serviceOffering,omitempty" tf:"service_offering,omitempty"`

	// (Number) The number of managed instances.
	// The number of managed instances.
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`

	// (String) The exoscale_template (ID) to use when creating the managed instances.
	// The [exoscale_template](../data-sources/template.md) (ID) to use when creating the managed instances.
	TemplateID *string `json:"templateId,omitempty" tf:"template_id,omitempty"`

	// init configuration to apply to the managed instances.
	// [cloud-init](http://cloudinit.readthedocs.io/) configuration to apply to the managed instances.
	UserData *string `json:"userData,omitempty" tf:"user_data,omitempty"`

	// (Set of String, Deprecated) The list of managed instances (IDs). Please use the instances.*.id attribute instead.
	// The list of managed instances (IDs). Please use the `instances.*.id` attribute instead.
	// +listType=set
	VirtualMachines []*string `json:"virtualMachines,omitempty" tf:"virtual_machines,omitempty"`

	// (String) ❗ The Exoscale Zone name.
	// ❗ The Exoscale [Zone](https://www.exoscale.com/datacenters/) name.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type InstancePoolObservation struct {

	// (Set of String, Deprecated) A list of exoscale_anti_affinity_group (IDs; may only be set at creation time).
	// A list of [exoscale_anti_affinity_group](./anti_affinity_group.md) (IDs; may only be set at creation time).
	// +listType=set
	AffinityGroupIds []*string `json:"affinityGroupIds,omitempty" tf:"affinity_group_ids,omitempty"`

	// (Set of String) A list of exoscale_anti_affinity_group (IDs; may only be set at creation time).
	// A list of [exoscale_anti_affinity_group](./anti_affinity_group.md) (IDs; may only be set at creation time).
	// +listType=set
	AntiAffinityGroupIds []*string `json:"antiAffinityGroupIds,omitempty" tf:"anti_affinity_group_ids,omitempty"`

	// (String) A deploy target ID.
	// A deploy target ID.
	DeployTargetID *string `json:"deployTargetId,omitempty" tf:"deploy_target_id,omitempty"`

	// form text describing the pool.
	// A free-form text describing the pool.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Number) The managed instances disk size (GiB).
	// The managed instances disk size (GiB).
	DiskSize *float64 `json:"diskSize,omitempty" tf:"disk_size,omitempty"`

	// (Set of String) A list of exoscale_elastic_ip (IDs).
	// A list of [exoscale_elastic_ip](./elastic_ip.md) (IDs).
	// +listType=set
	ElasticIPIds []*string `json:"elasticIpIds,omitempty" tf:"elastic_ip_ids,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Enable IPv6 on managed instances (boolean; default: false).
	// Enable IPv6 on managed instances (boolean; default: `false`).
	IPv6 *bool `json:"ipv6,omitempty" tf:"ipv6,omitempty"`

	// (String) The string used to prefix managed instances name (default: pool).
	// The string used to prefix managed instances name (default: `pool`).
	InstancePrefix *string `json:"instancePrefix,omitempty" tf:"instance_prefix,omitempty"`

	// exo compute instance-type list - for the list of available types).
	// The managed compute instances type (`<family>.<size>`, e.g. `standard.medium`; use the [Exoscale CLI](https://github.com/exoscale/cli/) - `exo compute instance-type list` - for the list of available types).
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// (Block Set) The list of managed instances. Structure is documented below. (see below for nested schema)
	// The list of managed instances. Structure is documented below.
	Instances []InstancesObservation `json:"instances,omitempty" tf:"instances,omitempty"`

	// (String) The exoscale_ssh_key (name) to authorize in the managed instances.
	// The [exoscale_ssh_key](./ssh_key.md) (name) to authorize in the managed instances.
	KeyPair *string `json:"keyPair,omitempty" tf:"key_pair,omitempty"`

	// (Map of String) A map of key/value labels.
	// A map of key/value labels.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (Number) Minimum number of running Instances.
	// Minimum number of running Instances.
	MinAvailable *float64 `json:"minAvailable,omitempty" tf:"min_available,omitempty"`

	// (String) The instance pool name.
	// The instance pool name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Set of String) A list of exoscale_private_network (IDs).
	// A list of [exoscale_private_network](./private_network.md) (IDs).
	// +listType=set
	NetworkIds []*string `json:"networkIds,omitempty" tf:"network_ids,omitempty"`

	// (Set of String) A list of exoscale_security_group (IDs).
	// A list of [exoscale_security_group](./security_group.md) (IDs).
	// +listType=set
	SecurityGroupIds []*string `json:"securityGroupIds,omitempty" tf:"security_group_ids,omitempty"`

	// (String, Deprecated) The managed instances type. Please use the instance_type argument instead.
	// The managed instances type. Please use the `instance_type` argument instead.
	ServiceOffering *string `json:"serviceOffering,omitempty" tf:"service_offering,omitempty"`

	// (Number) The number of managed instances.
	// The number of managed instances.
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`

	// (String)
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// (String) The exoscale_template (ID) to use when creating the managed instances.
	// The [exoscale_template](../data-sources/template.md) (ID) to use when creating the managed instances.
	TemplateID *string `json:"templateId,omitempty" tf:"template_id,omitempty"`

	// init configuration to apply to the managed instances.
	// [cloud-init](http://cloudinit.readthedocs.io/) configuration to apply to the managed instances.
	UserData *string `json:"userData,omitempty" tf:"user_data,omitempty"`

	// (Set of String, Deprecated) The list of managed instances (IDs). Please use the instances.*.id attribute instead.
	// The list of managed instances (IDs). Please use the `instances.*.id` attribute instead.
	// +listType=set
	VirtualMachines []*string `json:"virtualMachines,omitempty" tf:"virtual_machines,omitempty"`

	// (String) ❗ The Exoscale Zone name.
	// ❗ The Exoscale [Zone](https://www.exoscale.com/datacenters/) name.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type InstancePoolParameters struct {

	// (Set of String, Deprecated) A list of exoscale_anti_affinity_group (IDs; may only be set at creation time).
	// A list of [exoscale_anti_affinity_group](./anti_affinity_group.md) (IDs; may only be set at creation time).
	// +crossplane:generate:reference:type=github.com/exoscale/provider-exoscale/apis/namespaced/compute/v1alpha1.AntiAffinityGroup
	// +kubebuilder:validation:Optional
	// +listType=set
	AffinityGroupIds []*string `json:"affinityGroupIds,omitempty" tf:"affinity_group_ids,omitempty"`

	// References to AntiAffinityGroup in compute to populate affinityGroupIds.
	// +kubebuilder:validation:Optional
	AffinityGroupIdsRefs []v1.NamespacedReference `json:"affinityGroupIdsRefs,omitempty" tf:"-"`

	// Selector for a list of AntiAffinityGroup in compute to populate affinityGroupIds.
	// +kubebuilder:validation:Optional
	AffinityGroupIdsSelector *v1.NamespacedSelector `json:"affinityGroupIdsSelector,omitempty" tf:"-"`

	// (Set of String) A list of exoscale_anti_affinity_group (IDs; may only be set at creation time).
	// A list of [exoscale_anti_affinity_group](./anti_affinity_group.md) (IDs; may only be set at creation time).
	// +crossplane:generate:reference:type=github.com/exoscale/provider-exoscale/apis/namespaced/compute/v1alpha1.AntiAffinityGroup
	// +kubebuilder:validation:Optional
	// +listType=set
	AntiAffinityGroupIds []*string `json:"antiAffinityGroupIds,omitempty" tf:"anti_affinity_group_ids,omitempty"`

	// References to AntiAffinityGroup in compute to populate antiAffinityGroupIds.
	// +kubebuilder:validation:Optional
	AntiAffinityGroupIdsRefs []v1.NamespacedReference `json:"antiAffinityGroupIdsRefs,omitempty" tf:"-"`

	// Selector for a list of AntiAffinityGroup in compute to populate antiAffinityGroupIds.
	// +kubebuilder:validation:Optional
	AntiAffinityGroupIdsSelector *v1.NamespacedSelector `json:"antiAffinityGroupIdsSelector,omitempty" tf:"-"`

	// (String) A deploy target ID.
	// A deploy target ID.
	// +kubebuilder:validation:Optional
	DeployTargetID *string `json:"deployTargetId,omitempty" tf:"deploy_target_id,omitempty"`

	// form text describing the pool.
	// A free-form text describing the pool.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Number) The managed instances disk size (GiB).
	// The managed instances disk size (GiB).
	// +kubebuilder:validation:Optional
	DiskSize *float64 `json:"diskSize,omitempty" tf:"disk_size,omitempty"`

	// (Set of String) A list of exoscale_elastic_ip (IDs).
	// A list of [exoscale_elastic_ip](./elastic_ip.md) (IDs).
	// +crossplane:generate:reference:type=github.com/exoscale/provider-exoscale/apis/namespaced/compute/v1alpha1.ElasticIP
	// +kubebuilder:validation:Optional
	// +listType=set
	ElasticIPIds []*string `json:"elasticIpIds,omitempty" tf:"elastic_ip_ids,omitempty"`

	// References to ElasticIP in compute to populate elasticIpIds.
	// +kubebuilder:validation:Optional
	ElasticIPIdsRefs []v1.NamespacedReference `json:"elasticIpIdsRefs,omitempty" tf:"-"`

	// Selector for a list of ElasticIP in compute to populate elasticIpIds.
	// +kubebuilder:validation:Optional
	ElasticIPIdsSelector *v1.NamespacedSelector `json:"elasticIpIdsSelector,omitempty" tf:"-"`

	// (Boolean) Enable IPv6 on managed instances (boolean; default: false).
	// Enable IPv6 on managed instances (boolean; default: `false`).
	// +kubebuilder:validation:Optional
	IPv6 *bool `json:"ipv6,omitempty" tf:"ipv6,omitempty"`

	// (String) The string used to prefix managed instances name (default: pool).
	// The string used to prefix managed instances name (default: `pool`).
	// +kubebuilder:validation:Optional
	InstancePrefix *string `json:"instancePrefix,omitempty" tf:"instance_prefix,omitempty"`

	// exo compute instance-type list - for the list of available types).
	// The managed compute instances type (`<family>.<size>`, e.g. `standard.medium`; use the [Exoscale CLI](https://github.com/exoscale/cli/) - `exo compute instance-type list` - for the list of available types).
	// +kubebuilder:validation:Optional
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// (Block Set) The list of managed instances. Structure is documented below. (see below for nested schema)
	// The list of managed instances. Structure is documented below.
	// +kubebuilder:validation:Optional
	Instances []InstancesParameters `json:"instances,omitempty" tf:"instances,omitempty"`

	// (String) The exoscale_ssh_key (name) to authorize in the managed instances.
	// The [exoscale_ssh_key](./ssh_key.md) (name) to authorize in the managed instances.
	// +crossplane:generate:reference:type=github.com/exoscale/provider-exoscale/apis/namespaced/compute/v1alpha1.SSHKey
	// +kubebuilder:validation:Optional
	KeyPair *string `json:"keyPair,omitempty" tf:"key_pair,omitempty"`

	// Reference to a SSHKey in compute to populate keyPair.
	// +kubebuilder:validation:Optional
	KeyPairRef *v1.NamespacedReference `json:"keyPairRef,omitempty" tf:"-"`

	// Selector for a SSHKey in compute to populate keyPair.
	// +kubebuilder:validation:Optional
	KeyPairSelector *v1.NamespacedSelector `json:"keyPairSelector,omitempty" tf:"-"`

	// (Map of String) A map of key/value labels.
	// A map of key/value labels.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (Number) Minimum number of running Instances.
	// Minimum number of running Instances.
	// +kubebuilder:validation:Optional
	MinAvailable *float64 `json:"minAvailable,omitempty" tf:"min_available,omitempty"`

	// (String) The instance pool name.
	// The instance pool name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Set of String) A list of exoscale_private_network (IDs).
	// A list of [exoscale_private_network](./private_network.md) (IDs).
	// +crossplane:generate:reference:type=github.com/exoscale/provider-exoscale/apis/namespaced/compute/v1alpha1.PrivateNetwork
	// +kubebuilder:validation:Optional
	// +listType=set
	NetworkIds []*string `json:"networkIds,omitempty" tf:"network_ids,omitempty"`

	// References to PrivateNetwork in compute to populate networkIds.
	// +kubebuilder:validation:Optional
	NetworkIdsRefs []v1.NamespacedReference `json:"networkIdsRefs,omitempty" tf:"-"`

	// Selector for a list of PrivateNetwork in compute to populate networkIds.
	// +kubebuilder:validation:Optional
	NetworkIdsSelector *v1.NamespacedSelector `json:"networkIdsSelector,omitempty" tf:"-"`

	// (Set of String) A list of exoscale_security_group (IDs).
	// A list of [exoscale_security_group](./security_group.md) (IDs).
	// +crossplane:generate:reference:type=github.com/exoscale/provider-exoscale/apis/namespaced/compute/v1alpha1.SecurityGroup
	// +kubebuilder:validation:Optional
	// +listType=set
	SecurityGroupIds []*string `json:"securityGroupIds,omitempty" tf:"security_group_ids,omitempty"`

	// References to SecurityGroup in compute to populate securityGroupIds.
	// +kubebuilder:validation:Optional
	SecurityGroupIdsRefs []v1.NamespacedReference `json:"securityGroupIdsRefs,omitempty" tf:"-"`

	// Selector for a list of SecurityGroup in compute to populate securityGroupIds.
	// +kubebuilder:validation:Optional
	SecurityGroupIdsSelector *v1.NamespacedSelector `json:"securityGroupIdsSelector,omitempty" tf:"-"`

	// (String, Deprecated) The managed instances type. Please use the instance_type argument instead.
	// The managed instances type. Please use the `instance_type` argument instead.
	// +kubebuilder:validation:Optional
	ServiceOffering *string `json:"serviceOffering,omitempty" tf:"service_offering,omitempty"`

	// (Number) The number of managed instances.
	// The number of managed instances.
	// +kubebuilder:validation:Optional
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`

	// (String) The exoscale_template (ID) to use when creating the managed instances.
	// The [exoscale_template](../data-sources/template.md) (ID) to use when creating the managed instances.
	// +kubebuilder:validation:Optional
	TemplateID *string `json:"templateId,omitempty" tf:"template_id,omitempty"`

	// init configuration to apply to the managed instances.
	// [cloud-init](http://cloudinit.readthedocs.io/) configuration to apply to the managed instances.
	// +kubebuilder:validation:Optional
	UserData *string `json:"userData,omitempty" tf:"user_data,omitempty"`

	// (Set of String, Deprecated) The list of managed instances (IDs). Please use the instances.*.id attribute instead.
	// The list of managed instances (IDs). Please use the `instances.*.id` attribute instead.
	// +kubebuilder:validation:Optional
	// +listType=set
	VirtualMachines []*string `json:"virtualMachines,omitempty" tf:"virtual_machines,omitempty"`

	// (String) ❗ The Exoscale Zone name.
	// ❗ The Exoscale [Zone](https://www.exoscale.com/datacenters/) name.
	// +kubebuilder:validation:Optional
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type InstancesInitParameters struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The instance pool name.
	// The instance name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type InstancesObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The instance (main network interface) IPv6 address.
	// The instance (main network interface) IPv6 address.
	IPv6Address *string `json:"ipv6Address,omitempty" tf:"ipv6_address,omitempty"`

	// (String) The instance pool name.
	// The instance name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The instance (main network interface) IPv4 address.
	// The instance (main network interface) IPv4 address.
	PublicIPAddress *string `json:"publicIpAddress,omitempty" tf:"public_ip_address,omitempty"`
}

type InstancesParameters struct {

	// (String) The ID of this resource.
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The instance pool name.
	// The instance name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// InstancePoolSpec defines the desired state of InstancePool
type InstancePoolSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            InstancePoolParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider InstancePoolInitParameters `json:"initProvider,omitempty"`
}

// InstancePoolStatus defines the observed state of InstancePool.
type InstancePoolStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        InstancePoolObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// InstancePool is the Schema for the InstancePools API. Manage Exoscale Instance Pools https://community.exoscale.com/product/compute/instances/how-to/instance-pools/. Corresponding data sources: exoscaleinstancepool ../data-sources/instance_pool.md, exoscaleinstancepool_list ../data-sources/instance_pool_list.md.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,exoscale}
type InstancePool struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.size) || (has(self.initProvider) && has(self.initProvider.size))",message="spec.forProvider.size is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.templateId) || (has(self.initProvider) && has(self.initProvider.templateId))",message="spec.forProvider.templateId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.zone) || (has(self.initProvider) && has(self.initProvider.zone))",message="spec.forProvider.zone is a required parameter"
	Spec   InstancePoolSpec   `json:"spec"`
	Status InstancePoolStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// InstancePoolList contains a list of InstancePools
type InstancePoolList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []InstancePool `json:"items"`
}

// Repository type metadata.
var (
	InstancePool_Kind             = "InstancePool"
	InstancePool_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: InstancePool_Kind}.String()
	InstancePool_KindAPIVersion   = InstancePool_Kind + "." + CRDGroupVersion.String()
	InstancePool_GroupVersionKind = CRDGroupVersion.WithKind(InstancePool_Kind)
)

func init() {
	SchemeBuilder.Register(&InstancePool{}, &InstancePoolList{})
}
