// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type InstanceInitParameters struct {

	// (Set of String) ❗ A list of exoscale_anti_affinity_group (IDs) to attach to the instance (may only be set at creation time).
	// ❗ A list of [exoscale_anti_affinity_group](./anti_affinity_group.md) (IDs) to attach to the instance (may only be set at creation time).
	// +crossplane:generate:reference:type=github.com/exoscale/provider-exoscale/apis/namespaced/compute/v1alpha1.AntiAffinityGroup
	// +listType=set
	AntiAffinityGroupIds []*string `json:"antiAffinityGroupIds,omitempty" tf:"anti_affinity_group_ids,omitempty"`

	// References to AntiAffinityGroup in compute to populate antiAffinityGroupIds.
	// +kubebuilder:validation:Optional
	AntiAffinityGroupIdsRefs []v1.NamespacedReference `json:"antiAffinityGroupIdsRefs,omitempty" tf:"-"`

	// Selector for a list of AntiAffinityGroup in compute to populate antiAffinityGroupIds.
	// +kubebuilder:validation:Optional
	AntiAffinityGroupIdsSelector *v1.NamespacedSelector `json:"antiAffinityGroupIdsSelector,omitempty" tf:"-"`

	// (Set of String) A list of exoscale_block_storage_volume (ID) to attach to the instance.
	// A list of [exoscale_block_storage_volume](./block_storage_volume.md) (ID) to attach to the instance.
	// +crossplane:generate:reference:type=github.com/exoscale/provider-exoscale/apis/namespaced/compute/v1alpha1.BlockStorageVolume
	// +listType=set
	BlockStorageVolumeIds []*string `json:"blockStorageVolumeIds,omitempty" tf:"block_storage_volume_ids,omitempty"`

	// References to BlockStorageVolume in compute to populate blockStorageVolumeIds.
	// +kubebuilder:validation:Optional
	BlockStorageVolumeIdsRefs []v1.NamespacedReference `json:"blockStorageVolumeIdsRefs,omitempty" tf:"-"`

	// Selector for a list of BlockStorageVolume in compute to populate blockStorageVolumeIds.
	// +kubebuilder:validation:Optional
	BlockStorageVolumeIdsSelector *v1.NamespacedSelector `json:"blockStorageVolumeIdsSelector,omitempty" tf:"-"`

	// (String) ❗ A deploy target ID.
	// ❗ A deploy target ID.
	DeployTargetID *string `json:"deployTargetId,omitempty" tf:"deploy_target_id,omitempty"`

	// (Boolean) Mark the instance as protected, the Exoscale API will refuse to delete the instance until the protection is removed (boolean; default: false).
	// Mark the instance as protected, the Exoscale API will refuse to delete the instance until the protection is removed (boolean; default: `false`).
	DestroyProtected *bool `json:"destroyProtected,omitempty" tf:"destroy_protected,omitempty"`

	// (Number) The instance disk size (GiB; at least 10). Can not be decreased after creation. WARNING: updating this attribute stops/restarts the instance.
	// The instance disk size (GiB; at least `10`). Can not be decreased after creation. **WARNING**: updating this attribute stops/restarts the instance.
	DiskSize *float64 `json:"diskSize,omitempty" tf:"disk_size,omitempty"`

	// (Set of String) A list of exoscale_elastic_ip (IDs) to attach to the instance.
	// A list of [exoscale_elastic_ip](./elastic_ip.md) (IDs) to attach to the instance.
	// +crossplane:generate:reference:type=github.com/exoscale/provider-exoscale/apis/namespaced/compute/v1alpha1.ElasticIP
	// +listType=set
	ElasticIPIds []*string `json:"elasticIpIds,omitempty" tf:"elastic_ip_ids,omitempty"`

	// References to ElasticIP in compute to populate elasticIpIds.
	// +kubebuilder:validation:Optional
	ElasticIPIdsRefs []v1.NamespacedReference `json:"elasticIpIdsRefs,omitempty" tf:"-"`

	// Selector for a list of ElasticIP in compute to populate elasticIpIds.
	// +kubebuilder:validation:Optional
	ElasticIPIdsSelector *v1.NamespacedSelector `json:"elasticIpIdsSelector,omitempty" tf:"-"`

	// (Boolean) ❗ Enable secure boot on the instance (boolean; default: false). Can not be changed after the creation.
	// ❗ Enable secure boot on the instance (boolean; default: `false`). Can not be changed after the creation.
	EnableSecureBoot *bool `json:"enableSecureBoot,omitempty" tf:"enable_secure_boot,omitempty"`

	// (Boolean) Enable TPM on the instance (boolean; default: false). Can not be disabled after the creation. WARNING: enabling this attribute stops/restarts the instance.
	// Enable TPM on the instance (boolean; default: `false`). Can not be disabled after the creation. **WARNING**: enabling this attribute stops/restarts the instance.
	EnableTpm *bool `json:"enableTpm,omitempty" tf:"enable_tpm,omitempty"`

	// (Boolean) Enable IPv6 on the instance (boolean; default: false).
	// Enable IPv6 on the instance (boolean; default: `false`).
	IPv6 *bool `json:"ipv6,omitempty" tf:"ipv6,omitempty"`

	// (Map of String) A map of key/value labels.
	// A map of key/value labels.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The compute instance name.
	// The compute instance name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Block Set) Private network interfaces (may be specified multiple times). Structure is documented below. (see below for nested schema)
	// Private network interfaces (may be specified multiple times). Structure is documented below.
	NetworkInterface []NetworkInterfaceInitParameters `json:"networkInterface,omitempty" tf:"network_interface,omitempty"`

	// (Boolean) Whether the instance is private (no public IP addresses; default: false)
	// Whether the instance is private (no public IP addresses; default: false)
	Private *bool `json:"private,omitempty" tf:"private,omitempty"`

	// (String) Domain name for reverse DNS record.
	// Domain name for reverse DNS record.
	ReverseDNS *string `json:"reverseDns,omitempty" tf:"reverse_dns,omitempty"`

	// (String, Deprecated) ❗ The exoscale_ssh_key (name) to authorize in the instance (may only be set at creation time).
	// ❗ The [exoscale_ssh_key](./ssh_key.md) (name) to authorize in the instance (may only be set at creation time).
	SSHKey *string `json:"sshKey,omitempty" tf:"ssh_key,omitempty"`

	// (Set of String) ❗ The list of exoscale_ssh_key (name) to authorize in the instance (may only be set at creation time).
	// ❗ The list of [exoscale_ssh_key](./ssh_key.md) (name) to authorize in the instance (may only be set at creation time).
	// +crossplane:generate:reference:type=github.com/exoscale/provider-exoscale/apis/namespaced/compute/v1alpha1.SSHKey
	// +listType=set
	SSHKeys []*string `json:"sshKeys,omitempty" tf:"ssh_keys,omitempty"`

	// References to SSHKey in compute to populate sshKeys.
	// +kubebuilder:validation:Optional
	SSHKeysRefs []v1.NamespacedReference `json:"sshKeysRefs,omitempty" tf:"-"`

	// Selector for a list of SSHKey in compute to populate sshKeys.
	// +kubebuilder:validation:Optional
	SSHKeysSelector *v1.NamespacedSelector `json:"sshKeysSelector,omitempty" tf:"-"`

	// (Set of String) A list of exoscale_security_group (IDs) to attach to the instance.
	// A list of [exoscale_security_group](./security_group.md) (IDs) to attach to the instance.
	// +crossplane:generate:reference:type=github.com/exoscale/provider-exoscale/apis/namespaced/compute/v1alpha1.SecurityGroup
	// +listType=set
	SecurityGroupIds []*string `json:"securityGroupIds,omitempty" tf:"security_group_ids,omitempty"`

	// References to SecurityGroup in compute to populate securityGroupIds.
	// +kubebuilder:validation:Optional
	SecurityGroupIdsRefs []v1.NamespacedReference `json:"securityGroupIdsRefs,omitempty" tf:"-"`

	// Selector for a list of SecurityGroup in compute to populate securityGroupIds.
	// +kubebuilder:validation:Optional
	SecurityGroupIdsSelector *v1.NamespacedSelector `json:"securityGroupIdsSelector,omitempty" tf:"-"`

	// (String) The instance state (running or stopped; default: running).
	// The instance state (`running` or `stopped`; default: `running`).
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// (String) ❗ The exoscale_template (ID) to use when creating the instance.
	// ❗ The [exoscale_template](../data-sources/template.md) (ID) to use when creating the instance.
	TemplateID *string `json:"templateId,omitempty" tf:"template_id,omitempty"`

	// exo compute instance-type list - for the list of available types). WARNING: updating this attribute stops/restarts the instance.
	// The instance type (`<family>.<size>`, e.g. `standard.medium`; use the [Exoscale CLI](https://github.com/exoscale/cli/) - `exo compute instance-type list` - for the list of available types). **WARNING**: updating this attribute stops/restarts the instance.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// init configuration.
	// [cloud-init](https://cloudinit.readthedocs.io/) configuration.
	UserData *string `json:"userData,omitempty" tf:"user_data,omitempty"`

	// (String) ❗ The Exoscale Zone name.
	// ❗ The Exoscale [Zone](https://www.exoscale.com/datacenters/) name.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type InstanceObservation struct {

	// (Set of String) ❗ A list of exoscale_anti_affinity_group (IDs) to attach to the instance (may only be set at creation time).
	// ❗ A list of [exoscale_anti_affinity_group](./anti_affinity_group.md) (IDs) to attach to the instance (may only be set at creation time).
	// +listType=set
	AntiAffinityGroupIds []*string `json:"antiAffinityGroupIds,omitempty" tf:"anti_affinity_group_ids,omitempty"`

	// (Set of String) A list of exoscale_block_storage_volume (ID) to attach to the instance.
	// A list of [exoscale_block_storage_volume](./block_storage_volume.md) (ID) to attach to the instance.
	// +listType=set
	BlockStorageVolumeIds []*string `json:"blockStorageVolumeIds,omitempty" tf:"block_storage_volume_ids,omitempty"`

	// (String) The instance creation date.
	// The instance creation date.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) ❗ A deploy target ID.
	// ❗ A deploy target ID.
	DeployTargetID *string `json:"deployTargetId,omitempty" tf:"deploy_target_id,omitempty"`

	// (Boolean) Mark the instance as protected, the Exoscale API will refuse to delete the instance until the protection is removed (boolean; default: false).
	// Mark the instance as protected, the Exoscale API will refuse to delete the instance until the protection is removed (boolean; default: `false`).
	DestroyProtected *bool `json:"destroyProtected,omitempty" tf:"destroy_protected,omitempty"`

	// (Number) The instance disk size (GiB; at least 10). Can not be decreased after creation. WARNING: updating this attribute stops/restarts the instance.
	// The instance disk size (GiB; at least `10`). Can not be decreased after creation. **WARNING**: updating this attribute stops/restarts the instance.
	DiskSize *float64 `json:"diskSize,omitempty" tf:"disk_size,omitempty"`

	// (Set of String) A list of exoscale_elastic_ip (IDs) to attach to the instance.
	// A list of [exoscale_elastic_ip](./elastic_ip.md) (IDs) to attach to the instance.
	// +listType=set
	ElasticIPIds []*string `json:"elasticIpIds,omitempty" tf:"elastic_ip_ids,omitempty"`

	// (Boolean) ❗ Enable secure boot on the instance (boolean; default: false). Can not be changed after the creation.
	// ❗ Enable secure boot on the instance (boolean; default: `false`). Can not be changed after the creation.
	EnableSecureBoot *bool `json:"enableSecureBoot,omitempty" tf:"enable_secure_boot,omitempty"`

	// (Boolean) Enable TPM on the instance (boolean; default: false). Can not be disabled after the creation. WARNING: enabling this attribute stops/restarts the instance.
	// Enable TPM on the instance (boolean; default: `false`). Can not be disabled after the creation. **WARNING**: enabling this attribute stops/restarts the instance.
	EnableTpm *bool `json:"enableTpm,omitempty" tf:"enable_tpm,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Enable IPv6 on the instance (boolean; default: false).
	// Enable IPv6 on the instance (boolean; default: `false`).
	IPv6 *bool `json:"ipv6,omitempty" tf:"ipv6,omitempty"`

	// (String) The instance (main network interface) IPv6 address (if enabled).
	// The instance (main network interface) IPv6 address (if enabled).
	IPv6Address *string `json:"ipv6Address,omitempty" tf:"ipv6_address,omitempty"`

	// (Map of String) A map of key/value labels.
	// A map of key/value labels.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) MAC address
	// MAC address
	MacAddress *string `json:"macAddress,omitempty" tf:"mac_address,omitempty"`

	// (String) The compute instance name.
	// The compute instance name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Block Set) Private network interfaces (may be specified multiple times). Structure is documented below. (see below for nested schema)
	// Private network interfaces (may be specified multiple times). Structure is documented below.
	NetworkInterface []NetworkInterfaceObservation `json:"networkInterface,omitempty" tf:"network_interface,omitempty"`

	// (Boolean) Whether the instance is private (no public IP addresses; default: false)
	// Whether the instance is private (no public IP addresses; default: false)
	Private *bool `json:"private,omitempty" tf:"private,omitempty"`

	// (Set of String, Deprecated) A list of private networks (IDs) attached to the instance. Please use the network_interface.*.network_id argument instead.
	// A list of private networks (IDs) attached to the instance. Please use the `network_interface.*.network_id` argument instead.
	// +listType=set
	PrivateNetworkIds []*string `json:"privateNetworkIds,omitempty" tf:"private_network_ids,omitempty"`

	// (String) The instance (main network interface) IPv4 address.
	// The instance (main network interface) IPv4 address.
	PublicIPAddress *string `json:"publicIpAddress,omitempty" tf:"public_ip_address,omitempty"`

	// (String) Domain name for reverse DNS record.
	// Domain name for reverse DNS record.
	ReverseDNS *string `json:"reverseDns,omitempty" tf:"reverse_dns,omitempty"`

	// (String, Deprecated) ❗ The exoscale_ssh_key (name) to authorize in the instance (may only be set at creation time).
	// ❗ The [exoscale_ssh_key](./ssh_key.md) (name) to authorize in the instance (may only be set at creation time).
	SSHKey *string `json:"sshKey,omitempty" tf:"ssh_key,omitempty"`

	// (Set of String) ❗ The list of exoscale_ssh_key (name) to authorize in the instance (may only be set at creation time).
	// ❗ The list of [exoscale_ssh_key](./ssh_key.md) (name) to authorize in the instance (may only be set at creation time).
	// +listType=set
	SSHKeys []*string `json:"sshKeys,omitempty" tf:"ssh_keys,omitempty"`

	// (Set of String) A list of exoscale_security_group (IDs) to attach to the instance.
	// A list of [exoscale_security_group](./security_group.md) (IDs) to attach to the instance.
	// +listType=set
	SecurityGroupIds []*string `json:"securityGroupIds,omitempty" tf:"security_group_ids,omitempty"`

	// (String) The instance state (running or stopped; default: running).
	// The instance state (`running` or `stopped`; default: `running`).
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// (String) ❗ The exoscale_template (ID) to use when creating the instance.
	// ❗ The [exoscale_template](../data-sources/template.md) (ID) to use when creating the instance.
	TemplateID *string `json:"templateId,omitempty" tf:"template_id,omitempty"`

	// exo compute instance-type list - for the list of available types). WARNING: updating this attribute stops/restarts the instance.
	// The instance type (`<family>.<size>`, e.g. `standard.medium`; use the [Exoscale CLI](https://github.com/exoscale/cli/) - `exo compute instance-type list` - for the list of available types). **WARNING**: updating this attribute stops/restarts the instance.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// init configuration.
	// [cloud-init](https://cloudinit.readthedocs.io/) configuration.
	UserData *string `json:"userData,omitempty" tf:"user_data,omitempty"`

	// (String) ❗ The Exoscale Zone name.
	// ❗ The Exoscale [Zone](https://www.exoscale.com/datacenters/) name.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type InstanceParameters struct {

	// (Set of String) ❗ A list of exoscale_anti_affinity_group (IDs) to attach to the instance (may only be set at creation time).
	// ❗ A list of [exoscale_anti_affinity_group](./anti_affinity_group.md) (IDs) to attach to the instance (may only be set at creation time).
	// +crossplane:generate:reference:type=github.com/exoscale/provider-exoscale/apis/namespaced/compute/v1alpha1.AntiAffinityGroup
	// +kubebuilder:validation:Optional
	// +listType=set
	AntiAffinityGroupIds []*string `json:"antiAffinityGroupIds,omitempty" tf:"anti_affinity_group_ids,omitempty"`

	// References to AntiAffinityGroup in compute to populate antiAffinityGroupIds.
	// +kubebuilder:validation:Optional
	AntiAffinityGroupIdsRefs []v1.NamespacedReference `json:"antiAffinityGroupIdsRefs,omitempty" tf:"-"`

	// Selector for a list of AntiAffinityGroup in compute to populate antiAffinityGroupIds.
	// +kubebuilder:validation:Optional
	AntiAffinityGroupIdsSelector *v1.NamespacedSelector `json:"antiAffinityGroupIdsSelector,omitempty" tf:"-"`

	// (Set of String) A list of exoscale_block_storage_volume (ID) to attach to the instance.
	// A list of [exoscale_block_storage_volume](./block_storage_volume.md) (ID) to attach to the instance.
	// +crossplane:generate:reference:type=github.com/exoscale/provider-exoscale/apis/namespaced/compute/v1alpha1.BlockStorageVolume
	// +kubebuilder:validation:Optional
	// +listType=set
	BlockStorageVolumeIds []*string `json:"blockStorageVolumeIds,omitempty" tf:"block_storage_volume_ids,omitempty"`

	// References to BlockStorageVolume in compute to populate blockStorageVolumeIds.
	// +kubebuilder:validation:Optional
	BlockStorageVolumeIdsRefs []v1.NamespacedReference `json:"blockStorageVolumeIdsRefs,omitempty" tf:"-"`

	// Selector for a list of BlockStorageVolume in compute to populate blockStorageVolumeIds.
	// +kubebuilder:validation:Optional
	BlockStorageVolumeIdsSelector *v1.NamespacedSelector `json:"blockStorageVolumeIdsSelector,omitempty" tf:"-"`

	// (String) ❗ A deploy target ID.
	// ❗ A deploy target ID.
	// +kubebuilder:validation:Optional
	DeployTargetID *string `json:"deployTargetId,omitempty" tf:"deploy_target_id,omitempty"`

	// (Boolean) Mark the instance as protected, the Exoscale API will refuse to delete the instance until the protection is removed (boolean; default: false).
	// Mark the instance as protected, the Exoscale API will refuse to delete the instance until the protection is removed (boolean; default: `false`).
	// +kubebuilder:validation:Optional
	DestroyProtected *bool `json:"destroyProtected,omitempty" tf:"destroy_protected,omitempty"`

	// (Number) The instance disk size (GiB; at least 10). Can not be decreased after creation. WARNING: updating this attribute stops/restarts the instance.
	// The instance disk size (GiB; at least `10`). Can not be decreased after creation. **WARNING**: updating this attribute stops/restarts the instance.
	// +kubebuilder:validation:Optional
	DiskSize *float64 `json:"diskSize,omitempty" tf:"disk_size,omitempty"`

	// (Set of String) A list of exoscale_elastic_ip (IDs) to attach to the instance.
	// A list of [exoscale_elastic_ip](./elastic_ip.md) (IDs) to attach to the instance.
	// +crossplane:generate:reference:type=github.com/exoscale/provider-exoscale/apis/namespaced/compute/v1alpha1.ElasticIP
	// +kubebuilder:validation:Optional
	// +listType=set
	ElasticIPIds []*string `json:"elasticIpIds,omitempty" tf:"elastic_ip_ids,omitempty"`

	// References to ElasticIP in compute to populate elasticIpIds.
	// +kubebuilder:validation:Optional
	ElasticIPIdsRefs []v1.NamespacedReference `json:"elasticIpIdsRefs,omitempty" tf:"-"`

	// Selector for a list of ElasticIP in compute to populate elasticIpIds.
	// +kubebuilder:validation:Optional
	ElasticIPIdsSelector *v1.NamespacedSelector `json:"elasticIpIdsSelector,omitempty" tf:"-"`

	// (Boolean) ❗ Enable secure boot on the instance (boolean; default: false). Can not be changed after the creation.
	// ❗ Enable secure boot on the instance (boolean; default: `false`). Can not be changed after the creation.
	// +kubebuilder:validation:Optional
	EnableSecureBoot *bool `json:"enableSecureBoot,omitempty" tf:"enable_secure_boot,omitempty"`

	// (Boolean) Enable TPM on the instance (boolean; default: false). Can not be disabled after the creation. WARNING: enabling this attribute stops/restarts the instance.
	// Enable TPM on the instance (boolean; default: `false`). Can not be disabled after the creation. **WARNING**: enabling this attribute stops/restarts the instance.
	// +kubebuilder:validation:Optional
	EnableTpm *bool `json:"enableTpm,omitempty" tf:"enable_tpm,omitempty"`

	// (Boolean) Enable IPv6 on the instance (boolean; default: false).
	// Enable IPv6 on the instance (boolean; default: `false`).
	// +kubebuilder:validation:Optional
	IPv6 *bool `json:"ipv6,omitempty" tf:"ipv6,omitempty"`

	// (Map of String) A map of key/value labels.
	// A map of key/value labels.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The compute instance name.
	// The compute instance name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Block Set) Private network interfaces (may be specified multiple times). Structure is documented below. (see below for nested schema)
	// Private network interfaces (may be specified multiple times). Structure is documented below.
	// +kubebuilder:validation:Optional
	NetworkInterface []NetworkInterfaceParameters `json:"networkInterface,omitempty" tf:"network_interface,omitempty"`

	// (Boolean) Whether the instance is private (no public IP addresses; default: false)
	// Whether the instance is private (no public IP addresses; default: false)
	// +kubebuilder:validation:Optional
	Private *bool `json:"private,omitempty" tf:"private,omitempty"`

	// (String) Domain name for reverse DNS record.
	// Domain name for reverse DNS record.
	// +kubebuilder:validation:Optional
	ReverseDNS *string `json:"reverseDns,omitempty" tf:"reverse_dns,omitempty"`

	// (String, Deprecated) ❗ The exoscale_ssh_key (name) to authorize in the instance (may only be set at creation time).
	// ❗ The [exoscale_ssh_key](./ssh_key.md) (name) to authorize in the instance (may only be set at creation time).
	// +kubebuilder:validation:Optional
	SSHKey *string `json:"sshKey,omitempty" tf:"ssh_key,omitempty"`

	// (Set of String) ❗ The list of exoscale_ssh_key (name) to authorize in the instance (may only be set at creation time).
	// ❗ The list of [exoscale_ssh_key](./ssh_key.md) (name) to authorize in the instance (may only be set at creation time).
	// +crossplane:generate:reference:type=github.com/exoscale/provider-exoscale/apis/namespaced/compute/v1alpha1.SSHKey
	// +kubebuilder:validation:Optional
	// +listType=set
	SSHKeys []*string `json:"sshKeys,omitempty" tf:"ssh_keys,omitempty"`

	// References to SSHKey in compute to populate sshKeys.
	// +kubebuilder:validation:Optional
	SSHKeysRefs []v1.NamespacedReference `json:"sshKeysRefs,omitempty" tf:"-"`

	// Selector for a list of SSHKey in compute to populate sshKeys.
	// +kubebuilder:validation:Optional
	SSHKeysSelector *v1.NamespacedSelector `json:"sshKeysSelector,omitempty" tf:"-"`

	// (Set of String) A list of exoscale_security_group (IDs) to attach to the instance.
	// A list of [exoscale_security_group](./security_group.md) (IDs) to attach to the instance.
	// +crossplane:generate:reference:type=github.com/exoscale/provider-exoscale/apis/namespaced/compute/v1alpha1.SecurityGroup
	// +kubebuilder:validation:Optional
	// +listType=set
	SecurityGroupIds []*string `json:"securityGroupIds,omitempty" tf:"security_group_ids,omitempty"`

	// References to SecurityGroup in compute to populate securityGroupIds.
	// +kubebuilder:validation:Optional
	SecurityGroupIdsRefs []v1.NamespacedReference `json:"securityGroupIdsRefs,omitempty" tf:"-"`

	// Selector for a list of SecurityGroup in compute to populate securityGroupIds.
	// +kubebuilder:validation:Optional
	SecurityGroupIdsSelector *v1.NamespacedSelector `json:"securityGroupIdsSelector,omitempty" tf:"-"`

	// (String) The instance state (running or stopped; default: running).
	// The instance state (`running` or `stopped`; default: `running`).
	// +kubebuilder:validation:Optional
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// (String) ❗ The exoscale_template (ID) to use when creating the instance.
	// ❗ The [exoscale_template](../data-sources/template.md) (ID) to use when creating the instance.
	// +kubebuilder:validation:Optional
	TemplateID *string `json:"templateId,omitempty" tf:"template_id,omitempty"`

	// exo compute instance-type list - for the list of available types). WARNING: updating this attribute stops/restarts the instance.
	// The instance type (`<family>.<size>`, e.g. `standard.medium`; use the [Exoscale CLI](https://github.com/exoscale/cli/) - `exo compute instance-type list` - for the list of available types). **WARNING**: updating this attribute stops/restarts the instance.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// init configuration.
	// [cloud-init](https://cloudinit.readthedocs.io/) configuration.
	// +kubebuilder:validation:Optional
	UserData *string `json:"userData,omitempty" tf:"user_data,omitempty"`

	// (String) ❗ The Exoscale Zone name.
	// ❗ The Exoscale [Zone](https://www.exoscale.com/datacenters/) name.
	// +kubebuilder:validation:Optional
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type NetworkInterfaceInitParameters struct {

	// (String) The IPv4 address to request as static DHCP lease if the network interface is attached to a managed private network.
	// The IPv4 address to request as static DHCP lease if the network interface is attached to a *managed* private network.
	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`

	// (String) The exoscale_private_network (ID) to attach to the instance.
	// The [exoscale_private_network](./private_network.md) (ID) to attach to the instance.
	// +crossplane:generate:reference:type=github.com/exoscale/provider-exoscale/apis/namespaced/compute/v1alpha1.PrivateNetwork
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// Reference to a PrivateNetwork in compute to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDRef *v1.NamespacedReference `json:"networkIdRef,omitempty" tf:"-"`

	// Selector for a PrivateNetwork in compute to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDSelector *v1.NamespacedSelector `json:"networkIdSelector,omitempty" tf:"-"`
}

type NetworkInterfaceObservation struct {

	// (String) The IPv4 address to request as static DHCP lease if the network interface is attached to a managed private network.
	// The IPv4 address to request as static DHCP lease if the network interface is attached to a *managed* private network.
	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`

	// (String) MAC address
	// MAC address
	MacAddress *string `json:"macAddress,omitempty" tf:"mac_address,omitempty"`

	// (String) The exoscale_private_network (ID) to attach to the instance.
	// The [exoscale_private_network](./private_network.md) (ID) to attach to the instance.
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`
}

type NetworkInterfaceParameters struct {

	// (String) The IPv4 address to request as static DHCP lease if the network interface is attached to a managed private network.
	// The IPv4 address to request as static DHCP lease if the network interface is attached to a *managed* private network.
	// +kubebuilder:validation:Optional
	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`

	// (String) The exoscale_private_network (ID) to attach to the instance.
	// The [exoscale_private_network](./private_network.md) (ID) to attach to the instance.
	// +crossplane:generate:reference:type=github.com/exoscale/provider-exoscale/apis/namespaced/compute/v1alpha1.PrivateNetwork
	// +kubebuilder:validation:Optional
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// Reference to a PrivateNetwork in compute to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDRef *v1.NamespacedReference `json:"networkIdRef,omitempty" tf:"-"`

	// Selector for a PrivateNetwork in compute to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDSelector *v1.NamespacedSelector `json:"networkIdSelector,omitempty" tf:"-"`
}

// InstanceSpec defines the desired state of Instance
type InstanceSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            InstanceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider InstanceInitParameters `json:"initProvider,omitempty"`
}

// InstanceStatus defines the observed state of Instance.
type InstanceStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        InstanceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Instance is the Schema for the Instances API. Manage Exoscale Compute Instances https://community.exoscale.com/documentation/compute/. Corresponding data sources: exoscalecomputeinstance ../data-sources/compute_instance.md, exoscalecomputeinstance_list ../data-sources/compute_instance_list.md. After the creation, you can retrieve the password of an instance with Exoscale CLI https://github.com/exoscale/cli: exo compute instance reveal-password NAME.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,exoscale}
type Instance struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.diskSize) || (has(self.initProvider) && has(self.initProvider.diskSize))",message="spec.forProvider.diskSize is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.templateId) || (has(self.initProvider) && has(self.initProvider.templateId))",message="spec.forProvider.templateId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.zone) || (has(self.initProvider) && has(self.initProvider.zone))",message="spec.forProvider.zone is a required parameter"
	Spec   InstanceSpec   `json:"spec"`
	Status InstanceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// InstanceList contains a list of Instances
type InstanceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Instance `json:"items"`
}

// Repository type metadata.
var (
	Instance_Kind             = "Instance"
	Instance_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Instance_Kind}.String()
	Instance_KindAPIVersion   = Instance_Kind + "." + CRDGroupVersion.String()
	Instance_GroupVersionKind = CRDGroupVersion.WithKind(Instance_Kind)
)

func init() {
	SchemeBuilder.Register(&Instance{}, &InstanceList{})
}
