// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type SecurityGroupRulesInitParameters struct {

	// (String) ❗ An (INGRESS) source / (EGRESS) destination IP subnet (in CIDR notation) to match (conflicts with public_security_group/user_security_group/user_security_group_id).
	// ❗ An (`INGRESS`) source / (`EGRESS`) destination IP subnet (in [CIDR notation](https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing#CIDR_notation)) to match (conflicts with `public_security_group`/`user_security_group`/`user_security_group_id`).
	Cidr *string `json:"cidr,omitempty" tf:"cidr,omitempty"`

	// form text describing the security group rule.
	// ❗ A free-form text describing the security group rule.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Number) ❗ A TCP/UDP port range to match.
	// ❗ A `TCP`/`UDP` port range to match.
	EndPort *float64 `json:"endPort,omitempty" tf:"end_port,omitempty"`

	// (Number) ❗ An ICMP/ICMPv6 type/code to match.
	// ❗ An ICMP/ICMPv6 [type/code](https://en.wikipedia.org/wiki/Internet_Control_Message_Protocol#Control_messages) to match.
	IcmpCode *float64 `json:"icmpCode,omitempty" tf:"icmp_code,omitempty"`

	// (Number) ❗ An ICMP/ICMPv6 type/code to match.
	// ❗ An ICMP/ICMPv6 [type/code](https://en.wikipedia.org/wiki/Internet_Control_Message_Protocol#Control_messages) to match.
	IcmpType *float64 `json:"icmpType,omitempty" tf:"icmp_type,omitempty"`

	// (String) ❗ The network protocol to match (TCP, UDP, ICMP, ICMPv6, AH, ESP, GRE, IPIP or ALL)
	// ❗ The network protocol to match (`TCP`, `UDP`, `ICMP`, `ICMPv6`, `AH`, `ESP`, `GRE`, `IPIP` or `ALL`)
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// (String) ❗ An (INGRESS) source / (EGRESS) destination public security group name to match (conflicts with cidr/user_security_group/user_security_group_id).
	// ❗ An (`INGRESS`) source / (`EGRESS`) destination public security group name to match (conflicts with `cidr`/`user_security_group`/`user_security_group_id`).
	PublicSecurityGroup *string `json:"publicSecurityGroup,omitempty" tf:"public_security_group,omitempty"`

	// (String, Deprecated) ❗ The parent security group name. Please use the security_group_id argument along the exoscale_security_group data source instead.
	// ❗ The parent security group name. Please use the `security_group_id` argument along the [exoscale_security_group](../data-sources/security_group.md) data source instead.
	SecurityGroup *string `json:"securityGroup,omitempty" tf:"security_group,omitempty"`

	// (String) ❗ The parent exoscale_security_group ID.
	// ❗ The parent [exoscale_security_group](./security_group.md) ID.
	// +crossplane:generate:reference:type=github.com/exoscale/provider-exoscale/apis/namespaced/compute/v1alpha1.SecurityGroup
	SecurityGroupID *string `json:"securityGroupId,omitempty" tf:"security_group_id,omitempty"`

	// Reference to a SecurityGroup in compute to populate securityGroupId.
	// +kubebuilder:validation:Optional
	SecurityGroupIDRef *v1.NamespacedReference `json:"securityGroupIdRef,omitempty" tf:"-"`

	// Selector for a SecurityGroup in compute to populate securityGroupId.
	// +kubebuilder:validation:Optional
	SecurityGroupIDSelector *v1.NamespacedSelector `json:"securityGroupIdSelector,omitempty" tf:"-"`

	// (Number) ❗ A TCP/UDP port range to match.
	// ❗ A `TCP`/`UDP` port range to match.
	StartPort *float64 `json:"startPort,omitempty" tf:"start_port,omitempty"`

	// (String) ❗ The traffic direction to match (INGRESS or EGRESS).
	// ❗ The traffic direction to match (`INGRESS` or `EGRESS`).
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String, Deprecated) ❗ An (INGRESS) source / (EGRESS) destination security group name to match (conflicts with cidr/public_security_group/user_security_group_id). Please use the user_security_group_id argument along the exoscale_security_group data source instead.
	// ❗ An (`INGRESS`) source / (`EGRESS`) destination security group name to match (conflicts with `cidr`/`public_security_group`/`user_security_group_id`). Please use the `user_security_group_id` argument along the [exoscale_security_group](../data-sources/security_group.md) data source instead.
	UserSecurityGroup *string `json:"userSecurityGroup,omitempty" tf:"user_security_group,omitempty"`

	// (String) ❗ An (INGRESS) source / (EGRESS) destination security group ID to match (conflicts with cidr/public_security_group/user_security_group)).
	// ❗ An (`INGRESS`) source / (`EGRESS`) destination security group ID to match (conflicts with `cidr`/`public_security_group`/`user_security_group)`).
	UserSecurityGroupID *string `json:"userSecurityGroupId,omitempty" tf:"user_security_group_id,omitempty"`
}

type SecurityGroupRulesObservation struct {

	// (String) ❗ An (INGRESS) source / (EGRESS) destination IP subnet (in CIDR notation) to match (conflicts with public_security_group/user_security_group/user_security_group_id).
	// ❗ An (`INGRESS`) source / (`EGRESS`) destination IP subnet (in [CIDR notation](https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing#CIDR_notation)) to match (conflicts with `public_security_group`/`user_security_group`/`user_security_group_id`).
	Cidr *string `json:"cidr,omitempty" tf:"cidr,omitempty"`

	// form text describing the security group rule.
	// ❗ A free-form text describing the security group rule.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Number) ❗ A TCP/UDP port range to match.
	// ❗ A `TCP`/`UDP` port range to match.
	EndPort *float64 `json:"endPort,omitempty" tf:"end_port,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Number) ❗ An ICMP/ICMPv6 type/code to match.
	// ❗ An ICMP/ICMPv6 [type/code](https://en.wikipedia.org/wiki/Internet_Control_Message_Protocol#Control_messages) to match.
	IcmpCode *float64 `json:"icmpCode,omitempty" tf:"icmp_code,omitempty"`

	// (Number) ❗ An ICMP/ICMPv6 type/code to match.
	// ❗ An ICMP/ICMPv6 [type/code](https://en.wikipedia.org/wiki/Internet_Control_Message_Protocol#Control_messages) to match.
	IcmpType *float64 `json:"icmpType,omitempty" tf:"icmp_type,omitempty"`

	// (String) ❗ The network protocol to match (TCP, UDP, ICMP, ICMPv6, AH, ESP, GRE, IPIP or ALL)
	// ❗ The network protocol to match (`TCP`, `UDP`, `ICMP`, `ICMPv6`, `AH`, `ESP`, `GRE`, `IPIP` or `ALL`)
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// (String) ❗ An (INGRESS) source / (EGRESS) destination public security group name to match (conflicts with cidr/user_security_group/user_security_group_id).
	// ❗ An (`INGRESS`) source / (`EGRESS`) destination public security group name to match (conflicts with `cidr`/`user_security_group`/`user_security_group_id`).
	PublicSecurityGroup *string `json:"publicSecurityGroup,omitempty" tf:"public_security_group,omitempty"`

	// (String, Deprecated) ❗ The parent security group name. Please use the security_group_id argument along the exoscale_security_group data source instead.
	// ❗ The parent security group name. Please use the `security_group_id` argument along the [exoscale_security_group](../data-sources/security_group.md) data source instead.
	SecurityGroup *string `json:"securityGroup,omitempty" tf:"security_group,omitempty"`

	// (String) ❗ The parent exoscale_security_group ID.
	// ❗ The parent [exoscale_security_group](./security_group.md) ID.
	SecurityGroupID *string `json:"securityGroupId,omitempty" tf:"security_group_id,omitempty"`

	// (Number) ❗ A TCP/UDP port range to match.
	// ❗ A `TCP`/`UDP` port range to match.
	StartPort *float64 `json:"startPort,omitempty" tf:"start_port,omitempty"`

	// (String) ❗ The traffic direction to match (INGRESS or EGRESS).
	// ❗ The traffic direction to match (`INGRESS` or `EGRESS`).
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String, Deprecated) ❗ An (INGRESS) source / (EGRESS) destination security group name to match (conflicts with cidr/public_security_group/user_security_group_id). Please use the user_security_group_id argument along the exoscale_security_group data source instead.
	// ❗ An (`INGRESS`) source / (`EGRESS`) destination security group name to match (conflicts with `cidr`/`public_security_group`/`user_security_group_id`). Please use the `user_security_group_id` argument along the [exoscale_security_group](../data-sources/security_group.md) data source instead.
	UserSecurityGroup *string `json:"userSecurityGroup,omitempty" tf:"user_security_group,omitempty"`

	// (String) ❗ An (INGRESS) source / (EGRESS) destination security group ID to match (conflicts with cidr/public_security_group/user_security_group)).
	// ❗ An (`INGRESS`) source / (`EGRESS`) destination security group ID to match (conflicts with `cidr`/`public_security_group`/`user_security_group)`).
	UserSecurityGroupID *string `json:"userSecurityGroupId,omitempty" tf:"user_security_group_id,omitempty"`
}

type SecurityGroupRulesParameters struct {

	// (String) ❗ An (INGRESS) source / (EGRESS) destination IP subnet (in CIDR notation) to match (conflicts with public_security_group/user_security_group/user_security_group_id).
	// ❗ An (`INGRESS`) source / (`EGRESS`) destination IP subnet (in [CIDR notation](https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing#CIDR_notation)) to match (conflicts with `public_security_group`/`user_security_group`/`user_security_group_id`).
	// +kubebuilder:validation:Optional
	Cidr *string `json:"cidr,omitempty" tf:"cidr,omitempty"`

	// form text describing the security group rule.
	// ❗ A free-form text describing the security group rule.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Number) ❗ A TCP/UDP port range to match.
	// ❗ A `TCP`/`UDP` port range to match.
	// +kubebuilder:validation:Optional
	EndPort *float64 `json:"endPort,omitempty" tf:"end_port,omitempty"`

	// (Number) ❗ An ICMP/ICMPv6 type/code to match.
	// ❗ An ICMP/ICMPv6 [type/code](https://en.wikipedia.org/wiki/Internet_Control_Message_Protocol#Control_messages) to match.
	// +kubebuilder:validation:Optional
	IcmpCode *float64 `json:"icmpCode,omitempty" tf:"icmp_code,omitempty"`

	// (Number) ❗ An ICMP/ICMPv6 type/code to match.
	// ❗ An ICMP/ICMPv6 [type/code](https://en.wikipedia.org/wiki/Internet_Control_Message_Protocol#Control_messages) to match.
	// +kubebuilder:validation:Optional
	IcmpType *float64 `json:"icmpType,omitempty" tf:"icmp_type,omitempty"`

	// (String) ❗ The network protocol to match (TCP, UDP, ICMP, ICMPv6, AH, ESP, GRE, IPIP or ALL)
	// ❗ The network protocol to match (`TCP`, `UDP`, `ICMP`, `ICMPv6`, `AH`, `ESP`, `GRE`, `IPIP` or `ALL`)
	// +kubebuilder:validation:Optional
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// (String) ❗ An (INGRESS) source / (EGRESS) destination public security group name to match (conflicts with cidr/user_security_group/user_security_group_id).
	// ❗ An (`INGRESS`) source / (`EGRESS`) destination public security group name to match (conflicts with `cidr`/`user_security_group`/`user_security_group_id`).
	// +kubebuilder:validation:Optional
	PublicSecurityGroup *string `json:"publicSecurityGroup,omitempty" tf:"public_security_group,omitempty"`

	// (String, Deprecated) ❗ The parent security group name. Please use the security_group_id argument along the exoscale_security_group data source instead.
	// ❗ The parent security group name. Please use the `security_group_id` argument along the [exoscale_security_group](../data-sources/security_group.md) data source instead.
	// +kubebuilder:validation:Optional
	SecurityGroup *string `json:"securityGroup,omitempty" tf:"security_group,omitempty"`

	// (String) ❗ The parent exoscale_security_group ID.
	// ❗ The parent [exoscale_security_group](./security_group.md) ID.
	// +crossplane:generate:reference:type=github.com/exoscale/provider-exoscale/apis/namespaced/compute/v1alpha1.SecurityGroup
	// +kubebuilder:validation:Optional
	SecurityGroupID *string `json:"securityGroupId,omitempty" tf:"security_group_id,omitempty"`

	// Reference to a SecurityGroup in compute to populate securityGroupId.
	// +kubebuilder:validation:Optional
	SecurityGroupIDRef *v1.NamespacedReference `json:"securityGroupIdRef,omitempty" tf:"-"`

	// Selector for a SecurityGroup in compute to populate securityGroupId.
	// +kubebuilder:validation:Optional
	SecurityGroupIDSelector *v1.NamespacedSelector `json:"securityGroupIdSelector,omitempty" tf:"-"`

	// (Number) ❗ A TCP/UDP port range to match.
	// ❗ A `TCP`/`UDP` port range to match.
	// +kubebuilder:validation:Optional
	StartPort *float64 `json:"startPort,omitempty" tf:"start_port,omitempty"`

	// (String) ❗ The traffic direction to match (INGRESS or EGRESS).
	// ❗ The traffic direction to match (`INGRESS` or `EGRESS`).
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String, Deprecated) ❗ An (INGRESS) source / (EGRESS) destination security group name to match (conflicts with cidr/public_security_group/user_security_group_id). Please use the user_security_group_id argument along the exoscale_security_group data source instead.
	// ❗ An (`INGRESS`) source / (`EGRESS`) destination security group name to match (conflicts with `cidr`/`public_security_group`/`user_security_group_id`). Please use the `user_security_group_id` argument along the [exoscale_security_group](../data-sources/security_group.md) data source instead.
	// +kubebuilder:validation:Optional
	UserSecurityGroup *string `json:"userSecurityGroup,omitempty" tf:"user_security_group,omitempty"`

	// (String) ❗ An (INGRESS) source / (EGRESS) destination security group ID to match (conflicts with cidr/public_security_group/user_security_group)).
	// ❗ An (`INGRESS`) source / (`EGRESS`) destination security group ID to match (conflicts with `cidr`/`public_security_group`/`user_security_group)`).
	// +kubebuilder:validation:Optional
	UserSecurityGroupID *string `json:"userSecurityGroupId,omitempty" tf:"user_security_group_id,omitempty"`
}

// SecurityGroupRulesSpec defines the desired state of SecurityGroupRules
type SecurityGroupRulesSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            SecurityGroupRulesParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SecurityGroupRulesInitParameters `json:"initProvider,omitempty"`
}

// SecurityGroupRulesStatus defines the observed state of SecurityGroupRules.
type SecurityGroupRulesStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SecurityGroupRulesObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SecurityGroupRules is the Schema for the SecurityGroupRuless API. Manage Exoscale Security Group https://community.exoscale.com/product/networking/security-group/ Rules.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,exoscale}
type SecurityGroupRules struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   SecurityGroupRulesSpec   `json:"spec"`
	Status SecurityGroupRulesStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SecurityGroupRulesList contains a list of SecurityGroupRuless
type SecurityGroupRulesList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SecurityGroupRules `json:"items"`
}

// Repository type metadata.
var (
	SecurityGroupRules_Kind             = "SecurityGroupRules"
	SecurityGroupRules_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SecurityGroupRules_Kind}.String()
	SecurityGroupRules_KindAPIVersion   = SecurityGroupRules_Kind + "." + CRDGroupVersion.String()
	SecurityGroupRules_GroupVersionKind = CRDGroupVersion.WithKind(SecurityGroupRules_Kind)
)

func init() {
	SchemeBuilder.Register(&SecurityGroupRules{}, &SecurityGroupRulesList{})
}
