// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type DBAASDatabasePGInitParameters struct {

	// ❗ The name of the database for this service.
	DatabaseName *string `json:"databaseName,omitempty" tf:"database_name,omitempty"`

	// Default string sort order (LC_COLLATE) for PostgreSQL database
	LcCollate *string `json:"lcCollate,omitempty" tf:"lc_collate,omitempty"`

	// Default character classification (LC_CTYPE) for PostgreSQL database
	LcCtype *string `json:"lcCtype,omitempty" tf:"lc_ctype,omitempty"`

	// ❗ The name of the database service.
	// +crossplane:generate:reference:type=github.com/exoscale/provider-exoscale/apis/cluster/dbaas/v1alpha1.DBAASService
	Service *string `json:"service,omitempty" tf:"service,omitempty"`

	// Reference to a DBAASService in dbaas to populate service.
	// +kubebuilder:validation:Optional
	ServiceRef *v1.Reference `json:"serviceRef,omitempty" tf:"-"`

	// Selector for a DBAASService in dbaas to populate service.
	// +kubebuilder:validation:Optional
	ServiceSelector *v1.Selector `json:"serviceSelector,omitempty" tf:"-"`

	// ❗ The Exoscale [Zone](https://www.exoscale.com/datacenters/) name.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type DBAASDatabasePGObservation struct {

	// ❗ The name of the database for this service.
	DatabaseName *string `json:"databaseName,omitempty" tf:"database_name,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Default string sort order (LC_COLLATE) for PostgreSQL database
	LcCollate *string `json:"lcCollate,omitempty" tf:"lc_collate,omitempty"`

	// Default character classification (LC_CTYPE) for PostgreSQL database
	LcCtype *string `json:"lcCtype,omitempty" tf:"lc_ctype,omitempty"`

	// ❗ The name of the database service.
	Service *string `json:"service,omitempty" tf:"service,omitempty"`

	// ❗ The Exoscale [Zone](https://www.exoscale.com/datacenters/) name.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type DBAASDatabasePGParameters struct {

	// ❗ The name of the database for this service.
	// +kubebuilder:validation:Optional
	DatabaseName *string `json:"databaseName,omitempty" tf:"database_name,omitempty"`

	// Default string sort order (LC_COLLATE) for PostgreSQL database
	// +kubebuilder:validation:Optional
	LcCollate *string `json:"lcCollate,omitempty" tf:"lc_collate,omitempty"`

	// Default character classification (LC_CTYPE) for PostgreSQL database
	// +kubebuilder:validation:Optional
	LcCtype *string `json:"lcCtype,omitempty" tf:"lc_ctype,omitempty"`

	// ❗ The name of the database service.
	// +crossplane:generate:reference:type=github.com/exoscale/provider-exoscale/apis/cluster/dbaas/v1alpha1.DBAASService
	// +kubebuilder:validation:Optional
	Service *string `json:"service,omitempty" tf:"service,omitempty"`

	// Reference to a DBAASService in dbaas to populate service.
	// +kubebuilder:validation:Optional
	ServiceRef *v1.Reference `json:"serviceRef,omitempty" tf:"-"`

	// Selector for a DBAASService in dbaas to populate service.
	// +kubebuilder:validation:Optional
	ServiceSelector *v1.Selector `json:"serviceSelector,omitempty" tf:"-"`

	// ❗ The Exoscale [Zone](https://www.exoscale.com/datacenters/) name.
	// +kubebuilder:validation:Optional
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

// DBAASDatabasePGSpec defines the desired state of DBAASDatabasePG
type DBAASDatabasePGSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     DBAASDatabasePGParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DBAASDatabasePGInitParameters `json:"initProvider,omitempty"`
}

// DBAASDatabasePGStatus defines the observed state of DBAASDatabasePG.
type DBAASDatabasePGStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DBAASDatabasePGObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DBAASDatabasePG is the Schema for the DBAASDatabasePGs API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,exoscale}
type DBAASDatabasePG struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.databaseName) || (has(self.initProvider) && has(self.initProvider.databaseName))",message="spec.forProvider.databaseName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.zone) || (has(self.initProvider) && has(self.initProvider.zone))",message="spec.forProvider.zone is a required parameter"
	Spec   DBAASDatabasePGSpec   `json:"spec"`
	Status DBAASDatabasePGStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DBAASDatabasePGList contains a list of DBAASDatabasePGs
type DBAASDatabasePGList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DBAASDatabasePG `json:"items"`
}

// Repository type metadata.
var (
	DBAASDatabasePG_Kind             = "DBAASDatabasePG"
	DBAASDatabasePG_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DBAASDatabasePG_Kind}.String()
	DBAASDatabasePG_KindAPIVersion   = DBAASDatabasePG_Kind + "." + CRDGroupVersion.String()
	DBAASDatabasePG_GroupVersionKind = CRDGroupVersion.WithKind(DBAASDatabasePG_Kind)
)

func init() {
	SchemeBuilder.Register(&DBAASDatabasePG{}, &DBAASDatabasePGList{})
}
