// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type DBAASServiceInitParameters struct {
	Grafana *GrafanaInitParameters `json:"grafana,omitempty" tf:"grafana,omitempty"`

	Kafka *KafkaInitParameters `json:"kafka,omitempty" tf:"kafka,omitempty"`

	// The day of week to perform the automated database service maintenance (`never`, `monday`, `tuesday`, `wednesday`, `thursday`, `friday`, `saturday`, `sunday`).
	MaintenanceDow *string `json:"maintenanceDow,omitempty" tf:"maintenance_dow,omitempty"`

	// The time of day to perform the automated database service maintenance (`HH:MM:SS`)
	MaintenanceTime *string `json:"maintenanceTime,omitempty" tf:"maintenance_time,omitempty"`

	MySQL *MySQLInitParameters `json:"mysql,omitempty" tf:"mysql,omitempty"`

	// ❗ The name of the database service.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Opensearch *OpensearchInitParameters `json:"opensearch,omitempty" tf:"opensearch,omitempty"`

	Pg *PgInitParameters `json:"pg,omitempty" tf:"pg,omitempty"`

	// The plan of the database service (use the [Exoscale CLI](https://github.com/exoscale/cli/) - `exo dbaas type show <TYPE> --plans` - for reference).
	Plan *string `json:"plan,omitempty" tf:"plan,omitempty"`

	// The database service protection boolean flag against termination/power-off.
	TerminationProtection *bool `json:"terminationProtection,omitempty" tf:"termination_protection,omitempty"`

	// ❗ The type of the database service (`kafka`, `mysql`, `opensearch`, `pg`, `valkey`, `grafana`).
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	Valkey *ValkeyInitParameters `json:"valkey,omitempty" tf:"valkey,omitempty"`

	// ❗ The Exoscale [Zone](https://www.exoscale.com/datacenters/) name.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type DBAASServiceObservation struct {

	// The creation date of the database service.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// The disk size of the database service.
	DiskSize *float64 `json:"diskSize,omitempty" tf:"disk_size,omitempty"`

	Grafana *GrafanaObservation `json:"grafana,omitempty" tf:"grafana,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Kafka *KafkaObservation `json:"kafka,omitempty" tf:"kafka,omitempty"`

	// The day of week to perform the automated database service maintenance (`never`, `monday`, `tuesday`, `wednesday`, `thursday`, `friday`, `saturday`, `sunday`).
	MaintenanceDow *string `json:"maintenanceDow,omitempty" tf:"maintenance_dow,omitempty"`

	// The time of day to perform the automated database service maintenance (`HH:MM:SS`)
	MaintenanceTime *string `json:"maintenanceTime,omitempty" tf:"maintenance_time,omitempty"`

	MySQL *MySQLObservation `json:"mysql,omitempty" tf:"mysql,omitempty"`

	// ❗ The name of the database service.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The number of CPUs of the database service.
	NodeCpus *float64 `json:"nodeCpus,omitempty" tf:"node_cpus,omitempty"`

	// The amount of memory of the database service.
	NodeMemory *float64 `json:"nodeMemory,omitempty" tf:"node_memory,omitempty"`

	// The number of nodes of the database service.
	Nodes *float64 `json:"nodes,omitempty" tf:"nodes,omitempty"`

	Opensearch *OpensearchObservation `json:"opensearch,omitempty" tf:"opensearch,omitempty"`

	Pg *PgObservation `json:"pg,omitempty" tf:"pg,omitempty"`

	// The plan of the database service (use the [Exoscale CLI](https://github.com/exoscale/cli/) - `exo dbaas type show <TYPE> --plans` - for reference).
	Plan *string `json:"plan,omitempty" tf:"plan,omitempty"`

	// The current state of the database service.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// The database service protection boolean flag against termination/power-off.
	TerminationProtection *bool `json:"terminationProtection,omitempty" tf:"termination_protection,omitempty"`

	// ❗ The type of the database service (`kafka`, `mysql`, `opensearch`, `pg`, `valkey`, `grafana`).
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// The date of the latest database service update.
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	Valkey *ValkeyObservation `json:"valkey,omitempty" tf:"valkey,omitempty"`

	// ❗ The Exoscale [Zone](https://www.exoscale.com/datacenters/) name.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type DBAASServiceParameters struct {

	// +kubebuilder:validation:Optional
	Grafana *GrafanaParameters `json:"grafana,omitempty" tf:"grafana,omitempty"`

	// +kubebuilder:validation:Optional
	Kafka *KafkaParameters `json:"kafka,omitempty" tf:"kafka,omitempty"`

	// The day of week to perform the automated database service maintenance (`never`, `monday`, `tuesday`, `wednesday`, `thursday`, `friday`, `saturday`, `sunday`).
	// +kubebuilder:validation:Optional
	MaintenanceDow *string `json:"maintenanceDow,omitempty" tf:"maintenance_dow,omitempty"`

	// The time of day to perform the automated database service maintenance (`HH:MM:SS`)
	// +kubebuilder:validation:Optional
	MaintenanceTime *string `json:"maintenanceTime,omitempty" tf:"maintenance_time,omitempty"`

	// +kubebuilder:validation:Optional
	MySQL *MySQLParameters `json:"mysql,omitempty" tf:"mysql,omitempty"`

	// ❗ The name of the database service.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +kubebuilder:validation:Optional
	Opensearch *OpensearchParameters `json:"opensearch,omitempty" tf:"opensearch,omitempty"`

	// +kubebuilder:validation:Optional
	Pg *PgParameters `json:"pg,omitempty" tf:"pg,omitempty"`

	// The plan of the database service (use the [Exoscale CLI](https://github.com/exoscale/cli/) - `exo dbaas type show <TYPE> --plans` - for reference).
	// +kubebuilder:validation:Optional
	Plan *string `json:"plan,omitempty" tf:"plan,omitempty"`

	// The database service protection boolean flag against termination/power-off.
	// +kubebuilder:validation:Optional
	TerminationProtection *bool `json:"terminationProtection,omitempty" tf:"termination_protection,omitempty"`

	// ❗ The type of the database service (`kafka`, `mysql`, `opensearch`, `pg`, `valkey`, `grafana`).
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// +kubebuilder:validation:Optional
	Valkey *ValkeyParameters `json:"valkey,omitempty" tf:"valkey,omitempty"`

	// ❗ The Exoscale [Zone](https://www.exoscale.com/datacenters/) name.
	// +kubebuilder:validation:Optional
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type DashboardsInitParameters struct {

	// Enable or disable OpenSearch Dashboards (default: true).
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Limits the maximum amount of memory (in MiB) the OpenSearch Dashboards process can use. This sets the max_old_space_size option of the nodejs running the OpenSearch Dashboards. Note: the memory reserved by OpenSearch Dashboards is not available for OpenSearch. (default: 128).
	MaxOldSpaceSize *float64 `json:"maxOldSpaceSize,omitempty" tf:"max_old_space_size,omitempty"`

	// Timeout in milliseconds for requests made by OpenSearch Dashboards towards OpenSearch (default: 30000)
	RequestTimeout *float64 `json:"requestTimeout,omitempty" tf:"request_timeout,omitempty"`
}

type DashboardsObservation struct {

	// Enable or disable OpenSearch Dashboards (default: true).
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Limits the maximum amount of memory (in MiB) the OpenSearch Dashboards process can use. This sets the max_old_space_size option of the nodejs running the OpenSearch Dashboards. Note: the memory reserved by OpenSearch Dashboards is not available for OpenSearch. (default: 128).
	MaxOldSpaceSize *float64 `json:"maxOldSpaceSize,omitempty" tf:"max_old_space_size,omitempty"`

	// Timeout in milliseconds for requests made by OpenSearch Dashboards towards OpenSearch (default: 30000)
	RequestTimeout *float64 `json:"requestTimeout,omitempty" tf:"request_timeout,omitempty"`
}

type DashboardsParameters struct {

	// Enable or disable OpenSearch Dashboards (default: true).
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Limits the maximum amount of memory (in MiB) the OpenSearch Dashboards process can use. This sets the max_old_space_size option of the nodejs running the OpenSearch Dashboards. Note: the memory reserved by OpenSearch Dashboards is not available for OpenSearch. (default: 128).
	// +kubebuilder:validation:Optional
	MaxOldSpaceSize *float64 `json:"maxOldSpaceSize,omitempty" tf:"max_old_space_size,omitempty"`

	// Timeout in milliseconds for requests made by OpenSearch Dashboards towards OpenSearch (default: 30000)
	// +kubebuilder:validation:Optional
	RequestTimeout *float64 `json:"requestTimeout,omitempty" tf:"request_timeout,omitempty"`
}

type GrafanaInitParameters struct {

	// Grafana configuration settings in JSON format (`exo dbaas type show grafana --settings=grafana` for reference).
	GrafanaSettings *string `json:"grafanaSettings,omitempty" tf:"grafana_settings,omitempty"`

	// A list of CIDR blocks to allow incoming connections from.
	// +listType=set
	IPFilter []*string `json:"ipFilter,omitempty" tf:"ip_filter,omitempty"`
}

type GrafanaObservation struct {

	// Grafana configuration settings in JSON format (`exo dbaas type show grafana --settings=grafana` for reference).
	GrafanaSettings *string `json:"grafanaSettings,omitempty" tf:"grafana_settings,omitempty"`

	// A list of CIDR blocks to allow incoming connections from.
	// +listType=set
	IPFilter []*string `json:"ipFilter,omitempty" tf:"ip_filter,omitempty"`
}

type GrafanaParameters struct {

	// Grafana configuration settings in JSON format (`exo dbaas type show grafana --settings=grafana` for reference).
	// +kubebuilder:validation:Optional
	GrafanaSettings *string `json:"grafanaSettings,omitempty" tf:"grafana_settings,omitempty"`

	// A list of CIDR blocks to allow incoming connections from.
	// +kubebuilder:validation:Optional
	// +listType=set
	IPFilter []*string `json:"ipFilter,omitempty" tf:"ip_filter,omitempty"`
}

type IndexPatternInitParameters struct {

	// Maximum number of indexes to keep before deleting the oldest one (Minimum value is `0`)
	MaxIndexCount *float64 `json:"maxIndexCount,omitempty" tf:"max_index_count,omitempty"`

	// fnmatch pattern
	Pattern *string `json:"pattern,omitempty" tf:"pattern,omitempty"`

	// `alphabetical` or `creation_date`.
	SortingAlgorithm *string `json:"sortingAlgorithm,omitempty" tf:"sorting_algorithm,omitempty"`
}

type IndexPatternObservation struct {

	// Maximum number of indexes to keep before deleting the oldest one (Minimum value is `0`)
	MaxIndexCount *float64 `json:"maxIndexCount,omitempty" tf:"max_index_count,omitempty"`

	// fnmatch pattern
	Pattern *string `json:"pattern,omitempty" tf:"pattern,omitempty"`

	// `alphabetical` or `creation_date`.
	SortingAlgorithm *string `json:"sortingAlgorithm,omitempty" tf:"sorting_algorithm,omitempty"`
}

type IndexPatternParameters struct {

	// Maximum number of indexes to keep before deleting the oldest one (Minimum value is `0`)
	// +kubebuilder:validation:Optional
	MaxIndexCount *float64 `json:"maxIndexCount,omitempty" tf:"max_index_count,omitempty"`

	// fnmatch pattern
	// +kubebuilder:validation:Optional
	Pattern *string `json:"pattern,omitempty" tf:"pattern,omitempty"`

	// `alphabetical` or `creation_date`.
	// +kubebuilder:validation:Optional
	SortingAlgorithm *string `json:"sortingAlgorithm,omitempty" tf:"sorting_algorithm,omitempty"`
}

type IndexTemplateInitParameters struct {

	// The maximum number of nested JSON objects that a single document can contain across all nested types. This limit helps to prevent out of memory errors when a document contains too many nested objects. (Default is 10000. Minimum value is `0`, maximum value is `100000`.)
	MappingNestedObjectsLimit *float64 `json:"mappingNestedObjectsLimit,omitempty" tf:"mapping_nested_objects_limit,omitempty"`

	// The number of replicas each primary shard has. (Minimum value is `0`, maximum value is `29`)
	NumberOfReplicas *float64 `json:"numberOfReplicas,omitempty" tf:"number_of_replicas,omitempty"`

	// The number of primary shards that an index should have. (Minimum value is `1`, maximum value is `1024`.)
	NumberOfShards *float64 `json:"numberOfShards,omitempty" tf:"number_of_shards,omitempty"`
}

type IndexTemplateObservation struct {

	// The maximum number of nested JSON objects that a single document can contain across all nested types. This limit helps to prevent out of memory errors when a document contains too many nested objects. (Default is 10000. Minimum value is `0`, maximum value is `100000`.)
	MappingNestedObjectsLimit *float64 `json:"mappingNestedObjectsLimit,omitempty" tf:"mapping_nested_objects_limit,omitempty"`

	// The number of replicas each primary shard has. (Minimum value is `0`, maximum value is `29`)
	NumberOfReplicas *float64 `json:"numberOfReplicas,omitempty" tf:"number_of_replicas,omitempty"`

	// The number of primary shards that an index should have. (Minimum value is `1`, maximum value is `1024`.)
	NumberOfShards *float64 `json:"numberOfShards,omitempty" tf:"number_of_shards,omitempty"`
}

type IndexTemplateParameters struct {

	// The maximum number of nested JSON objects that a single document can contain across all nested types. This limit helps to prevent out of memory errors when a document contains too many nested objects. (Default is 10000. Minimum value is `0`, maximum value is `100000`.)
	// +kubebuilder:validation:Optional
	MappingNestedObjectsLimit *float64 `json:"mappingNestedObjectsLimit,omitempty" tf:"mapping_nested_objects_limit,omitempty"`

	// The number of replicas each primary shard has. (Minimum value is `0`, maximum value is `29`)
	// +kubebuilder:validation:Optional
	NumberOfReplicas *float64 `json:"numberOfReplicas,omitempty" tf:"number_of_replicas,omitempty"`

	// The number of primary shards that an index should have. (Minimum value is `1`, maximum value is `1024`.)
	// +kubebuilder:validation:Optional
	NumberOfShards *float64 `json:"numberOfShards,omitempty" tf:"number_of_shards,omitempty"`
}

type KafkaInitParameters struct {

	// Enable certificate-based authentication method.
	EnableCertAuth *bool `json:"enableCertAuth,omitempty" tf:"enable_cert_auth,omitempty"`

	// Enable Kafka Connect.
	EnableKafkaConnect *bool `json:"enableKafkaConnect,omitempty" tf:"enable_kafka_connect,omitempty"`

	// Enable Kafka REST.
	EnableKafkaRest *bool `json:"enableKafkaRest,omitempty" tf:"enable_kafka_rest,omitempty"`

	// Enable SASL-based authentication method.
	EnableSaslAuth *bool `json:"enableSaslAuth,omitempty" tf:"enable_sasl_auth,omitempty"`

	// Enable Schema Registry.
	EnableSchemaRegistry *bool `json:"enableSchemaRegistry,omitempty" tf:"enable_schema_registry,omitempty"`

	// A list of CIDR blocks to allow incoming connections from.
	// +listType=set
	IPFilter []*string `json:"ipFilter,omitempty" tf:"ip_filter,omitempty"`

	// Kafka Connect configuration settings in JSON format (`exo dbaas type show kafka --settings=kafka-connect` for reference).
	KafkaConnectSettings *string `json:"kafkaConnectSettings,omitempty" tf:"kafka_connect_settings,omitempty"`

	// Kafka REST configuration settings in JSON format (`exo dbaas type show kafka --settings=kafka-rest` for reference).
	KafkaRestSettings *string `json:"kafkaRestSettings,omitempty" tf:"kafka_rest_settings,omitempty"`

	// Kafka configuration settings in JSON format (`exo dbaas type show kafka --settings=kafka` for reference).
	KafkaSettings *string `json:"kafkaSettings,omitempty" tf:"kafka_settings,omitempty"`

	// Schema Registry configuration settings in JSON format (`exo dbaas type show kafka --settings=schema-registry` for reference)
	SchemaRegistrySettings *string `json:"schemaRegistrySettings,omitempty" tf:"schema_registry_settings,omitempty"`

	// Kafka major version (`exo dbaas type show kafka` for reference; may only be set at creation time).
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type KafkaObservation struct {

	// Enable certificate-based authentication method.
	EnableCertAuth *bool `json:"enableCertAuth,omitempty" tf:"enable_cert_auth,omitempty"`

	// Enable Kafka Connect.
	EnableKafkaConnect *bool `json:"enableKafkaConnect,omitempty" tf:"enable_kafka_connect,omitempty"`

	// Enable Kafka REST.
	EnableKafkaRest *bool `json:"enableKafkaRest,omitempty" tf:"enable_kafka_rest,omitempty"`

	// Enable SASL-based authentication method.
	EnableSaslAuth *bool `json:"enableSaslAuth,omitempty" tf:"enable_sasl_auth,omitempty"`

	// Enable Schema Registry.
	EnableSchemaRegistry *bool `json:"enableSchemaRegistry,omitempty" tf:"enable_schema_registry,omitempty"`

	// A list of CIDR blocks to allow incoming connections from.
	// +listType=set
	IPFilter []*string `json:"ipFilter,omitempty" tf:"ip_filter,omitempty"`

	// Kafka Connect configuration settings in JSON format (`exo dbaas type show kafka --settings=kafka-connect` for reference).
	KafkaConnectSettings *string `json:"kafkaConnectSettings,omitempty" tf:"kafka_connect_settings,omitempty"`

	// Kafka REST configuration settings in JSON format (`exo dbaas type show kafka --settings=kafka-rest` for reference).
	KafkaRestSettings *string `json:"kafkaRestSettings,omitempty" tf:"kafka_rest_settings,omitempty"`

	// Kafka configuration settings in JSON format (`exo dbaas type show kafka --settings=kafka` for reference).
	KafkaSettings *string `json:"kafkaSettings,omitempty" tf:"kafka_settings,omitempty"`

	// Schema Registry configuration settings in JSON format (`exo dbaas type show kafka --settings=schema-registry` for reference)
	SchemaRegistrySettings *string `json:"schemaRegistrySettings,omitempty" tf:"schema_registry_settings,omitempty"`

	// Kafka major version (`exo dbaas type show kafka` for reference; may only be set at creation time).
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type KafkaParameters struct {

	// Enable certificate-based authentication method.
	// +kubebuilder:validation:Optional
	EnableCertAuth *bool `json:"enableCertAuth,omitempty" tf:"enable_cert_auth,omitempty"`

	// Enable Kafka Connect.
	// +kubebuilder:validation:Optional
	EnableKafkaConnect *bool `json:"enableKafkaConnect,omitempty" tf:"enable_kafka_connect,omitempty"`

	// Enable Kafka REST.
	// +kubebuilder:validation:Optional
	EnableKafkaRest *bool `json:"enableKafkaRest,omitempty" tf:"enable_kafka_rest,omitempty"`

	// Enable SASL-based authentication method.
	// +kubebuilder:validation:Optional
	EnableSaslAuth *bool `json:"enableSaslAuth,omitempty" tf:"enable_sasl_auth,omitempty"`

	// Enable Schema Registry.
	// +kubebuilder:validation:Optional
	EnableSchemaRegistry *bool `json:"enableSchemaRegistry,omitempty" tf:"enable_schema_registry,omitempty"`

	// A list of CIDR blocks to allow incoming connections from.
	// +kubebuilder:validation:Optional
	// +listType=set
	IPFilter []*string `json:"ipFilter,omitempty" tf:"ip_filter,omitempty"`

	// Kafka Connect configuration settings in JSON format (`exo dbaas type show kafka --settings=kafka-connect` for reference).
	// +kubebuilder:validation:Optional
	KafkaConnectSettings *string `json:"kafkaConnectSettings,omitempty" tf:"kafka_connect_settings,omitempty"`

	// Kafka REST configuration settings in JSON format (`exo dbaas type show kafka --settings=kafka-rest` for reference).
	// +kubebuilder:validation:Optional
	KafkaRestSettings *string `json:"kafkaRestSettings,omitempty" tf:"kafka_rest_settings,omitempty"`

	// Kafka configuration settings in JSON format (`exo dbaas type show kafka --settings=kafka` for reference).
	// +kubebuilder:validation:Optional
	KafkaSettings *string `json:"kafkaSettings,omitempty" tf:"kafka_settings,omitempty"`

	// Schema Registry configuration settings in JSON format (`exo dbaas type show kafka --settings=schema-registry` for reference)
	// +kubebuilder:validation:Optional
	SchemaRegistrySettings *string `json:"schemaRegistrySettings,omitempty" tf:"schema_registry_settings,omitempty"`

	// Kafka major version (`exo dbaas type show kafka` for reference; may only be set at creation time).
	// +kubebuilder:validation:Optional
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type MySQLInitParameters struct {

	// A custom administrator account password (may only be set at creation time).
	AdminPasswordSecretRef *v1.LocalSecretKeySelector `json:"adminPasswordSecretRef,omitempty" tf:"-"`

	// A custom administrator account username (may only be set at creation time).
	AdminUsername *string `json:"adminUsername,omitempty" tf:"admin_username,omitempty"`

	// The automated backup schedule (`HH:MM`).
	BackupSchedule *string `json:"backupSchedule,omitempty" tf:"backup_schedule,omitempty"`

	// A list of CIDR blocks to allow incoming connections from.
	// +listType=set
	IPFilter []*string `json:"ipFilter,omitempty" tf:"ip_filter,omitempty"`

	// MySQL configuration settings in JSON format (`exo dbaas type show mysql --settings=mysql` for reference).
	MySQLSettings *string `json:"mysqlSettings,omitempty" tf:"mysql_settings,omitempty"`

	// MySQL major version (`exo dbaas type show mysql` for reference; may only be set at creation time).
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type MySQLObservation struct {

	// A custom administrator account username (may only be set at creation time).
	AdminUsername *string `json:"adminUsername,omitempty" tf:"admin_username,omitempty"`

	// The automated backup schedule (`HH:MM`).
	BackupSchedule *string `json:"backupSchedule,omitempty" tf:"backup_schedule,omitempty"`

	// A list of CIDR blocks to allow incoming connections from.
	// +listType=set
	IPFilter []*string `json:"ipFilter,omitempty" tf:"ip_filter,omitempty"`

	// MySQL configuration settings in JSON format (`exo dbaas type show mysql --settings=mysql` for reference).
	MySQLSettings *string `json:"mysqlSettings,omitempty" tf:"mysql_settings,omitempty"`

	// MySQL major version (`exo dbaas type show mysql` for reference; may only be set at creation time).
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type MySQLParameters struct {

	// A custom administrator account password (may only be set at creation time).
	// +kubebuilder:validation:Optional
	AdminPasswordSecretRef *v1.LocalSecretKeySelector `json:"adminPasswordSecretRef,omitempty" tf:"-"`

	// A custom administrator account username (may only be set at creation time).
	// +kubebuilder:validation:Optional
	AdminUsername *string `json:"adminUsername,omitempty" tf:"admin_username,omitempty"`

	// The automated backup schedule (`HH:MM`).
	// +kubebuilder:validation:Optional
	BackupSchedule *string `json:"backupSchedule,omitempty" tf:"backup_schedule,omitempty"`

	// A list of CIDR blocks to allow incoming connections from.
	// +kubebuilder:validation:Optional
	// +listType=set
	IPFilter []*string `json:"ipFilter,omitempty" tf:"ip_filter,omitempty"`

	// MySQL configuration settings in JSON format (`exo dbaas type show mysql --settings=mysql` for reference).
	// +kubebuilder:validation:Optional
	MySQLSettings *string `json:"mysqlSettings,omitempty" tf:"mysql_settings,omitempty"`

	// MySQL major version (`exo dbaas type show mysql` for reference; may only be set at creation time).
	// +kubebuilder:validation:Optional
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type OpensearchInitParameters struct {
	Dashboards *DashboardsInitParameters `json:"dashboards,omitempty" tf:"dashboards,omitempty"`

	// ❗ Service name
	ForkFromService *string `json:"forkFromService,omitempty" tf:"fork_from_service,omitempty"`

	// Allow incoming connections from this list of CIDR address block, e.g. `["10.20.0.0/16"]
	// +listType=set
	IPFilter []*string `json:"ipFilter,omitempty" tf:"ip_filter,omitempty"`

	IndexPattern []IndexPatternInitParameters `json:"indexPattern,omitempty" tf:"index_pattern,omitempty"`

	IndexTemplate *IndexTemplateInitParameters `json:"indexTemplate,omitempty" tf:"index_template,omitempty"`

	// Aiven automation resets index.refresh_interval to default value for every index to be sure that indices are always visible to search. If it doesn't fit your case, you can disable this by setting up this flag to true.
	KeepIndexRefreshInterval *bool `json:"keepIndexRefreshInterval,omitempty" tf:"keep_index_refresh_interval,omitempty"`

	// Maximum number of indexes to keep (Minimum value is `0`)
	MaxIndexCount *float64 `json:"maxIndexCount,omitempty" tf:"max_index_count,omitempty"`

	// ❗ Name of a backup to recover from
	RecoveryBackupName *string `json:"recoveryBackupName,omitempty" tf:"recovery_backup_name,omitempty"`

	// OpenSearch-specific settings, in json. e.g.`jsonencode({thread_pool_search_size: 64})`. Use `exo x get-dbaas-settings-opensearch` to get a list of available settings.
	Settings *string `json:"settings,omitempty" tf:"settings,omitempty"`

	// ❗ OpenSearch major version (`exo dbaas type show opensearch` for reference)
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type OpensearchObservation struct {
	Dashboards *DashboardsObservation `json:"dashboards,omitempty" tf:"dashboards,omitempty"`

	// ❗ Service name
	ForkFromService *string `json:"forkFromService,omitempty" tf:"fork_from_service,omitempty"`

	// Allow incoming connections from this list of CIDR address block, e.g. `["10.20.0.0/16"]
	// +listType=set
	IPFilter []*string `json:"ipFilter,omitempty" tf:"ip_filter,omitempty"`

	IndexPattern []IndexPatternObservation `json:"indexPattern,omitempty" tf:"index_pattern,omitempty"`

	IndexTemplate *IndexTemplateObservation `json:"indexTemplate,omitempty" tf:"index_template,omitempty"`

	// Aiven automation resets index.refresh_interval to default value for every index to be sure that indices are always visible to search. If it doesn't fit your case, you can disable this by setting up this flag to true.
	KeepIndexRefreshInterval *bool `json:"keepIndexRefreshInterval,omitempty" tf:"keep_index_refresh_interval,omitempty"`

	// Maximum number of indexes to keep (Minimum value is `0`)
	MaxIndexCount *float64 `json:"maxIndexCount,omitempty" tf:"max_index_count,omitempty"`

	// ❗ Name of a backup to recover from
	RecoveryBackupName *string `json:"recoveryBackupName,omitempty" tf:"recovery_backup_name,omitempty"`

	// OpenSearch-specific settings, in json. e.g.`jsonencode({thread_pool_search_size: 64})`. Use `exo x get-dbaas-settings-opensearch` to get a list of available settings.
	Settings *string `json:"settings,omitempty" tf:"settings,omitempty"`

	// ❗ OpenSearch major version (`exo dbaas type show opensearch` for reference)
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type OpensearchParameters struct {

	// +kubebuilder:validation:Optional
	Dashboards *DashboardsParameters `json:"dashboards,omitempty" tf:"dashboards,omitempty"`

	// ❗ Service name
	// +kubebuilder:validation:Optional
	ForkFromService *string `json:"forkFromService,omitempty" tf:"fork_from_service,omitempty"`

	// Allow incoming connections from this list of CIDR address block, e.g. `["10.20.0.0/16"]
	// +kubebuilder:validation:Optional
	// +listType=set
	IPFilter []*string `json:"ipFilter,omitempty" tf:"ip_filter,omitempty"`

	// +kubebuilder:validation:Optional
	IndexPattern []IndexPatternParameters `json:"indexPattern,omitempty" tf:"index_pattern,omitempty"`

	// +kubebuilder:validation:Optional
	IndexTemplate *IndexTemplateParameters `json:"indexTemplate,omitempty" tf:"index_template,omitempty"`

	// Aiven automation resets index.refresh_interval to default value for every index to be sure that indices are always visible to search. If it doesn't fit your case, you can disable this by setting up this flag to true.
	// +kubebuilder:validation:Optional
	KeepIndexRefreshInterval *bool `json:"keepIndexRefreshInterval,omitempty" tf:"keep_index_refresh_interval,omitempty"`

	// Maximum number of indexes to keep (Minimum value is `0`)
	// +kubebuilder:validation:Optional
	MaxIndexCount *float64 `json:"maxIndexCount,omitempty" tf:"max_index_count,omitempty"`

	// ❗ Name of a backup to recover from
	// +kubebuilder:validation:Optional
	RecoveryBackupName *string `json:"recoveryBackupName,omitempty" tf:"recovery_backup_name,omitempty"`

	// OpenSearch-specific settings, in json. e.g.`jsonencode({thread_pool_search_size: 64})`. Use `exo x get-dbaas-settings-opensearch` to get a list of available settings.
	// +kubebuilder:validation:Optional
	Settings *string `json:"settings,omitempty" tf:"settings,omitempty"`

	// ❗ OpenSearch major version (`exo dbaas type show opensearch` for reference)
	// +kubebuilder:validation:Optional
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type PgInitParameters struct {

	// A custom administrator account password (may only be set at creation time).
	AdminPasswordSecretRef *v1.LocalSecretKeySelector `json:"adminPasswordSecretRef,omitempty" tf:"-"`

	// A custom administrator account username (may only be set at creation time).
	AdminUsername *string `json:"adminUsername,omitempty" tf:"admin_username,omitempty"`

	// The automated backup schedule (`HH:MM`).
	BackupSchedule *string `json:"backupSchedule,omitempty" tf:"backup_schedule,omitempty"`

	// A list of CIDR blocks to allow incoming connections from.
	// +listType=set
	IPFilter []*string `json:"ipFilter,omitempty" tf:"ip_filter,omitempty"`

	// PostgreSQL configuration settings in JSON format (`exo dbaas type show pg --settings=pg` for reference).
	PgSettings *string `json:"pgSettings,omitempty" tf:"pg_settings,omitempty"`

	// PgBouncer configuration settings in JSON format (`exo dbaas type show pg --settings=pgbouncer` for reference).
	PgbouncerSettings *string `json:"pgbouncerSettings,omitempty" tf:"pgbouncer_settings,omitempty"`

	// pglookout configuration settings in JSON format (`exo dbaas type show pg --settings=pglookout` for reference).
	PglookoutSettings *string `json:"pglookoutSettings,omitempty" tf:"pglookout_settings,omitempty"`

	// PostgreSQL major version (`exo dbaas type show pg` for reference; may only be set at creation time).
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type PgObservation struct {

	// A custom administrator account username (may only be set at creation time).
	AdminUsername *string `json:"adminUsername,omitempty" tf:"admin_username,omitempty"`

	// The automated backup schedule (`HH:MM`).
	BackupSchedule *string `json:"backupSchedule,omitempty" tf:"backup_schedule,omitempty"`

	// A list of CIDR blocks to allow incoming connections from.
	// +listType=set
	IPFilter []*string `json:"ipFilter,omitempty" tf:"ip_filter,omitempty"`

	// PostgreSQL configuration settings in JSON format (`exo dbaas type show pg --settings=pg` for reference).
	PgSettings *string `json:"pgSettings,omitempty" tf:"pg_settings,omitempty"`

	// PgBouncer configuration settings in JSON format (`exo dbaas type show pg --settings=pgbouncer` for reference).
	PgbouncerSettings *string `json:"pgbouncerSettings,omitempty" tf:"pgbouncer_settings,omitempty"`

	// pglookout configuration settings in JSON format (`exo dbaas type show pg --settings=pglookout` for reference).
	PglookoutSettings *string `json:"pglookoutSettings,omitempty" tf:"pglookout_settings,omitempty"`

	// PostgreSQL major version (`exo dbaas type show pg` for reference; may only be set at creation time).
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type PgParameters struct {

	// A custom administrator account password (may only be set at creation time).
	// +kubebuilder:validation:Optional
	AdminPasswordSecretRef *v1.LocalSecretKeySelector `json:"adminPasswordSecretRef,omitempty" tf:"-"`

	// A custom administrator account username (may only be set at creation time).
	// +kubebuilder:validation:Optional
	AdminUsername *string `json:"adminUsername,omitempty" tf:"admin_username,omitempty"`

	// The automated backup schedule (`HH:MM`).
	// +kubebuilder:validation:Optional
	BackupSchedule *string `json:"backupSchedule,omitempty" tf:"backup_schedule,omitempty"`

	// A list of CIDR blocks to allow incoming connections from.
	// +kubebuilder:validation:Optional
	// +listType=set
	IPFilter []*string `json:"ipFilter,omitempty" tf:"ip_filter,omitempty"`

	// PostgreSQL configuration settings in JSON format (`exo dbaas type show pg --settings=pg` for reference).
	// +kubebuilder:validation:Optional
	PgSettings *string `json:"pgSettings,omitempty" tf:"pg_settings,omitempty"`

	// PgBouncer configuration settings in JSON format (`exo dbaas type show pg --settings=pgbouncer` for reference).
	// +kubebuilder:validation:Optional
	PgbouncerSettings *string `json:"pgbouncerSettings,omitempty" tf:"pgbouncer_settings,omitempty"`

	// pglookout configuration settings in JSON format (`exo dbaas type show pg --settings=pglookout` for reference).
	// +kubebuilder:validation:Optional
	PglookoutSettings *string `json:"pglookoutSettings,omitempty" tf:"pglookout_settings,omitempty"`

	// PostgreSQL major version (`exo dbaas type show pg` for reference; may only be set at creation time).
	// +kubebuilder:validation:Optional
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type ValkeyInitParameters struct {

	// A list of CIDR blocks to allow incoming connections from.
	// +listType=set
	IPFilter []*string `json:"ipFilter,omitempty" tf:"ip_filter,omitempty"`

	// Valkey configuration settings in JSON format (`exo dbaas type show valkey --settings=valkey` for reference).
	ValkeySettings *string `json:"valkeySettings,omitempty" tf:"valkey_settings,omitempty"`
}

type ValkeyObservation struct {

	// A list of CIDR blocks to allow incoming connections from.
	// +listType=set
	IPFilter []*string `json:"ipFilter,omitempty" tf:"ip_filter,omitempty"`

	// Valkey configuration settings in JSON format (`exo dbaas type show valkey --settings=valkey` for reference).
	ValkeySettings *string `json:"valkeySettings,omitempty" tf:"valkey_settings,omitempty"`
}

type ValkeyParameters struct {

	// A list of CIDR blocks to allow incoming connections from.
	// +kubebuilder:validation:Optional
	// +listType=set
	IPFilter []*string `json:"ipFilter,omitempty" tf:"ip_filter,omitempty"`

	// Valkey configuration settings in JSON format (`exo dbaas type show valkey --settings=valkey` for reference).
	// +kubebuilder:validation:Optional
	ValkeySettings *string `json:"valkeySettings,omitempty" tf:"valkey_settings,omitempty"`
}

// DBAASServiceSpec defines the desired state of DBAASService
type DBAASServiceSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            DBAASServiceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DBAASServiceInitParameters `json:"initProvider,omitempty"`
}

// DBAASServiceStatus defines the observed state of DBAASService.
type DBAASServiceStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DBAASServiceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DBAASService is the Schema for the DBAASServices API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,exoscale}
type DBAASService struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.plan) || (has(self.initProvider) && has(self.initProvider.plan))",message="spec.forProvider.plan is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.zone) || (has(self.initProvider) && has(self.initProvider.zone))",message="spec.forProvider.zone is a required parameter"
	Spec   DBAASServiceSpec   `json:"spec"`
	Status DBAASServiceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DBAASServiceList contains a list of DBAASServices
type DBAASServiceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DBAASService `json:"items"`
}

// Repository type metadata.
var (
	DBAASService_Kind             = "DBAASService"
	DBAASService_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DBAASService_Kind}.String()
	DBAASService_KindAPIVersion   = DBAASService_Kind + "." + CRDGroupVersion.String()
	DBAASService_GroupVersionKind = CRDGroupVersion.WithKind(DBAASService_Kind)
)

func init() {
	SchemeBuilder.Register(&DBAASService{}, &DBAASServiceList{})
}
