// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type DBAASUserKafkaInitParameters struct {

	// ❗ The name of the database service.
	// +crossplane:generate:reference:type=github.com/exoscale/provider-exoscale/apis/namespaced/dbaas/v1alpha1.DBAASService
	Service *string `json:"service,omitempty" tf:"service,omitempty"`

	// Reference to a DBAASService in dbaas to populate service.
	// +kubebuilder:validation:Optional
	ServiceRef *v1.NamespacedReference `json:"serviceRef,omitempty" tf:"-"`

	// Selector for a DBAASService in dbaas to populate service.
	// +kubebuilder:validation:Optional
	ServiceSelector *v1.NamespacedSelector `json:"serviceSelector,omitempty" tf:"-"`

	// ❗ The name of the user for this service.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`

	// ❗ The Exoscale [Zone](https://www.exoscale.com/datacenters/) name.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type DBAASUserKafkaObservation struct {

	// Access certificate expiry date.
	AccessCertExpiry *string `json:"accessCertExpiry,omitempty" tf:"access_cert_expiry,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// ❗ The name of the database service.
	Service *string `json:"service,omitempty" tf:"service,omitempty"`

	// The type of the service user.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// ❗ The name of the user for this service.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`

	// ❗ The Exoscale [Zone](https://www.exoscale.com/datacenters/) name.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type DBAASUserKafkaParameters struct {

	// ❗ The name of the database service.
	// +crossplane:generate:reference:type=github.com/exoscale/provider-exoscale/apis/namespaced/dbaas/v1alpha1.DBAASService
	// +kubebuilder:validation:Optional
	Service *string `json:"service,omitempty" tf:"service,omitempty"`

	// Reference to a DBAASService in dbaas to populate service.
	// +kubebuilder:validation:Optional
	ServiceRef *v1.NamespacedReference `json:"serviceRef,omitempty" tf:"-"`

	// Selector for a DBAASService in dbaas to populate service.
	// +kubebuilder:validation:Optional
	ServiceSelector *v1.NamespacedSelector `json:"serviceSelector,omitempty" tf:"-"`

	// ❗ The name of the user for this service.
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`

	// ❗ The Exoscale [Zone](https://www.exoscale.com/datacenters/) name.
	// +kubebuilder:validation:Optional
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

// DBAASUserKafkaSpec defines the desired state of DBAASUserKafka
type DBAASUserKafkaSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            DBAASUserKafkaParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DBAASUserKafkaInitParameters `json:"initProvider,omitempty"`
}

// DBAASUserKafkaStatus defines the observed state of DBAASUserKafka.
type DBAASUserKafkaStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DBAASUserKafkaObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DBAASUserKafka is the Schema for the DBAASUserKafkas API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,exoscale}
type DBAASUserKafka struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.username) || (has(self.initProvider) && has(self.initProvider.username))",message="spec.forProvider.username is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.zone) || (has(self.initProvider) && has(self.initProvider.zone))",message="spec.forProvider.zone is a required parameter"
	Spec   DBAASUserKafkaSpec   `json:"spec"`
	Status DBAASUserKafkaStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DBAASUserKafkaList contains a list of DBAASUserKafkas
type DBAASUserKafkaList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DBAASUserKafka `json:"items"`
}

// Repository type metadata.
var (
	DBAASUserKafka_Kind             = "DBAASUserKafka"
	DBAASUserKafka_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DBAASUserKafka_Kind}.String()
	DBAASUserKafka_KindAPIVersion   = DBAASUserKafka_Kind + "." + CRDGroupVersion.String()
	DBAASUserKafka_GroupVersionKind = CRDGroupVersion.WithKind(DBAASUserKafka_Kind)
)

func init() {
	SchemeBuilder.Register(&DBAASUserKafka{}, &DBAASUserKafkaList{})
}
