// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type BlockStorageVolumeInitParameters struct {

	// Resource labels.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Volume name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Volume size in GB (default 10). If volume is attached, instance must be stopped to update this value. Volume can only grow, cannot be shrunk.
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`

	SnapshotTarget *SnapshotTargetInitParameters `json:"snapshotTarget,omitempty" tf:"snapshot_target,omitempty"`

	// ❗ The Exoscale [Zone](https://www.exoscale.com/datacenters/) name.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type BlockStorageVolumeObservation struct {

	// Volume block size.
	Blocksize *float64 `json:"blocksize,omitempty" tf:"blocksize,omitempty"`

	// Volume creation date.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Resource labels.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Volume name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Volume size in GB (default 10). If volume is attached, instance must be stopped to update this value. Volume can only grow, cannot be shrunk.
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`

	SnapshotTarget *SnapshotTargetObservation `json:"snapshotTarget,omitempty" tf:"snapshot_target,omitempty"`

	// Volume state.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// ❗ The Exoscale [Zone](https://www.exoscale.com/datacenters/) name.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type BlockStorageVolumeParameters struct {

	// Resource labels.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Volume name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Volume size in GB (default 10). If volume is attached, instance must be stopped to update this value. Volume can only grow, cannot be shrunk.
	// +kubebuilder:validation:Optional
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`

	// +kubebuilder:validation:Optional
	SnapshotTarget *SnapshotTargetParameters `json:"snapshotTarget,omitempty" tf:"snapshot_target,omitempty"`

	// ❗ The Exoscale [Zone](https://www.exoscale.com/datacenters/) name.
	// +kubebuilder:validation:Optional
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type SnapshotTargetInitParameters struct {

	// Snapshot ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type SnapshotTargetObservation struct {

	// Snapshot ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type SnapshotTargetParameters struct {

	// Snapshot ID.
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

// BlockStorageVolumeSpec defines the desired state of BlockStorageVolume
type BlockStorageVolumeSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     BlockStorageVolumeParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider BlockStorageVolumeInitParameters `json:"initProvider,omitempty"`
}

// BlockStorageVolumeStatus defines the observed state of BlockStorageVolume.
type BlockStorageVolumeStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        BlockStorageVolumeObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// BlockStorageVolume is the Schema for the BlockStorageVolumes API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,exoscale}
type BlockStorageVolume struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.zone) || (has(self.initProvider) && has(self.initProvider.zone))",message="spec.forProvider.zone is a required parameter"
	Spec   BlockStorageVolumeSpec   `json:"spec"`
	Status BlockStorageVolumeStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BlockStorageVolumeList contains a list of BlockStorageVolumes
type BlockStorageVolumeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BlockStorageVolume `json:"items"`
}

// Repository type metadata.
var (
	BlockStorageVolume_Kind             = "BlockStorageVolume"
	BlockStorageVolume_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: BlockStorageVolume_Kind}.String()
	BlockStorageVolume_KindAPIVersion   = BlockStorageVolume_Kind + "." + CRDGroupVersion.String()
	BlockStorageVolume_GroupVersionKind = CRDGroupVersion.WithKind(BlockStorageVolume_Kind)
)

func init() {
	SchemeBuilder.Register(&BlockStorageVolume{}, &BlockStorageVolumeList{})
}
