// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type NLBInitParameters struct {

	// form text describing the NLB.
	// A free-form text describing the NLB.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Map of String) A map of key/value labels.
	// A map of key/value labels.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The network load balancer (NLB) name.
	// The network load balancer (NLB) name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) ❗ The Exoscale Zone name.
	// ❗ The Exoscale [Zone](https://www.exoscale.com/datacenters/) name.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type NLBObservation struct {

	// (String) The NLB creation date.
	// The NLB creation date.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// form text describing the NLB.
	// A free-form text describing the NLB.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The NLB IPv4 address.
	// The NLB IPv4 address.
	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`

	// (Map of String) A map of key/value labels.
	// A map of key/value labels.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The network load balancer (NLB) name.
	// The network load balancer (NLB) name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Set of String) The list of the exoscale_nlb_service (names).
	// The list of the [exoscale_nlb_service](./nlb_service.md) (names).
	// +listType=set
	Services []*string `json:"services,omitempty" tf:"services,omitempty"`

	// (String) The current NLB state.
	// The current NLB state.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// (String) ❗ The Exoscale Zone name.
	// ❗ The Exoscale [Zone](https://www.exoscale.com/datacenters/) name.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type NLBParameters struct {

	// form text describing the NLB.
	// A free-form text describing the NLB.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Map of String) A map of key/value labels.
	// A map of key/value labels.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The network load balancer (NLB) name.
	// The network load balancer (NLB) name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) ❗ The Exoscale Zone name.
	// ❗ The Exoscale [Zone](https://www.exoscale.com/datacenters/) name.
	// +kubebuilder:validation:Optional
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

// NLBSpec defines the desired state of NLB
type NLBSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     NLBParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider NLBInitParameters `json:"initProvider,omitempty"`
}

// NLBStatus defines the observed state of NLB.
type NLBStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        NLBObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// NLB is the Schema for the NLBs API. Manage Exoscale Network Load Balancers (NLB).
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,exoscale}
type NLB struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.zone) || (has(self.initProvider) && has(self.initProvider.zone))",message="spec.forProvider.zone is a required parameter"
	Spec   NLBSpec   `json:"spec"`
	Status NLBStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NLBList contains a list of NLBs
type NLBList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NLB `json:"items"`
}

// Repository type metadata.
var (
	NLB_Kind             = "NLB"
	NLB_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: NLB_Kind}.String()
	NLB_KindAPIVersion   = NLB_Kind + "." + CRDGroupVersion.String()
	NLB_GroupVersionKind = CRDGroupVersion.WithKind(NLB_Kind)
)

func init() {
	SchemeBuilder.Register(&NLB{}, &NLBList{})
}
