// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type PrivateNetworkInitParameters struct {

	// form text describing the network.
	// A free-form text describing the network.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) (For managed Privnets) The first/last IPv4 addresses used by the DHCP service for dynamic leases.
	// (For managed Privnets) The first/last IPv4 addresses used by the DHCP service for dynamic leases.
	EndIP *string `json:"endIp,omitempty" tf:"end_ip,omitempty"`

	// (Map of String) A map of key/value labels.
	// A map of key/value labels.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The private network name.
	// The private network name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) (For managed Privnets) The network mask defining the IPv4 network allowed for static leases.
	// (For managed Privnets) The network mask defining the IPv4 network allowed for static leases.
	Netmask *string `json:"netmask,omitempty" tf:"netmask,omitempty"`

	// (String) (For managed Privnets) The first/last IPv4 addresses used by the DHCP service for dynamic leases.
	// (For managed Privnets) The first/last IPv4 addresses used by the DHCP service for dynamic leases.
	StartIP *string `json:"startIp,omitempty" tf:"start_ip,omitempty"`

	// (String) ❗ The Exoscale Zone name.
	// ❗ The Exoscale [Zone](https://www.exoscale.com/datacenters/) name.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type PrivateNetworkObservation struct {

	// form text describing the network.
	// A free-form text describing the network.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) (For managed Privnets) The first/last IPv4 addresses used by the DHCP service for dynamic leases.
	// (For managed Privnets) The first/last IPv4 addresses used by the DHCP service for dynamic leases.
	EndIP *string `json:"endIp,omitempty" tf:"end_ip,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Map of String) A map of key/value labels.
	// A map of key/value labels.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The private network name.
	// The private network name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) (For managed Privnets) The network mask defining the IPv4 network allowed for static leases.
	// (For managed Privnets) The network mask defining the IPv4 network allowed for static leases.
	Netmask *string `json:"netmask,omitempty" tf:"netmask,omitempty"`

	// (String) (For managed Privnets) The first/last IPv4 addresses used by the DHCP service for dynamic leases.
	// (For managed Privnets) The first/last IPv4 addresses used by the DHCP service for dynamic leases.
	StartIP *string `json:"startIp,omitempty" tf:"start_ip,omitempty"`

	// (String) ❗ The Exoscale Zone name.
	// ❗ The Exoscale [Zone](https://www.exoscale.com/datacenters/) name.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type PrivateNetworkParameters struct {

	// form text describing the network.
	// A free-form text describing the network.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) (For managed Privnets) The first/last IPv4 addresses used by the DHCP service for dynamic leases.
	// (For managed Privnets) The first/last IPv4 addresses used by the DHCP service for dynamic leases.
	// +kubebuilder:validation:Optional
	EndIP *string `json:"endIp,omitempty" tf:"end_ip,omitempty"`

	// (Map of String) A map of key/value labels.
	// A map of key/value labels.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The private network name.
	// The private network name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) (For managed Privnets) The network mask defining the IPv4 network allowed for static leases.
	// (For managed Privnets) The network mask defining the IPv4 network allowed for static leases.
	// +kubebuilder:validation:Optional
	Netmask *string `json:"netmask,omitempty" tf:"netmask,omitempty"`

	// (String) (For managed Privnets) The first/last IPv4 addresses used by the DHCP service for dynamic leases.
	// (For managed Privnets) The first/last IPv4 addresses used by the DHCP service for dynamic leases.
	// +kubebuilder:validation:Optional
	StartIP *string `json:"startIp,omitempty" tf:"start_ip,omitempty"`

	// (String) ❗ The Exoscale Zone name.
	// ❗ The Exoscale [Zone](https://www.exoscale.com/datacenters/) name.
	// +kubebuilder:validation:Optional
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

// PrivateNetworkSpec defines the desired state of PrivateNetwork
type PrivateNetworkSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PrivateNetworkParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PrivateNetworkInitParameters `json:"initProvider,omitempty"`
}

// PrivateNetworkStatus defines the observed state of PrivateNetwork.
type PrivateNetworkStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PrivateNetworkObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// PrivateNetwork is the Schema for the PrivateNetworks API. Manage Exoscale Private Networks.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,exoscale}
type PrivateNetwork struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.zone) || (has(self.initProvider) && has(self.initProvider.zone))",message="spec.forProvider.zone is a required parameter"
	Spec   PrivateNetworkSpec   `json:"spec"`
	Status PrivateNetworkStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PrivateNetworkList contains a list of PrivateNetworks
type PrivateNetworkList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PrivateNetwork `json:"items"`
}

// Repository type metadata.
var (
	PrivateNetwork_Kind             = "PrivateNetwork"
	PrivateNetwork_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PrivateNetwork_Kind}.String()
	PrivateNetwork_KindAPIVersion   = PrivateNetwork_Kind + "." + CRDGroupVersion.String()
	PrivateNetwork_GroupVersionKind = CRDGroupVersion.WithKind(PrivateNetwork_Kind)
)

func init() {
	SchemeBuilder.Register(&PrivateNetwork{}, &PrivateNetworkList{})
}
