// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type KubeletImageGcInitParameters struct {

	// (Number) The percent of disk usage after which image garbage collection is always run
	// The percent of disk usage after which image garbage collection is always run
	HighThreshold *float64 `json:"highThreshold,omitempty" tf:"high_threshold,omitempty"`

	// (Number) The percent of disk usage before which image garbage collection is never run
	// The percent of disk usage before which image garbage collection is never run
	LowThreshold *float64 `json:"lowThreshold,omitempty" tf:"low_threshold,omitempty"`

	// (String) The minimum age for an unused image before it is garbage collected (k8s duration format, eg. 1h)
	// The minimum age for an unused image before it is garbage collected (k8s duration format, eg. 1h)
	MinAge *string `json:"minAge,omitempty" tf:"min_age,omitempty"`
}

type KubeletImageGcObservation struct {

	// (Number) The percent of disk usage after which image garbage collection is always run
	// The percent of disk usage after which image garbage collection is always run
	HighThreshold *float64 `json:"highThreshold,omitempty" tf:"high_threshold,omitempty"`

	// (Number) The percent of disk usage before which image garbage collection is never run
	// The percent of disk usage before which image garbage collection is never run
	LowThreshold *float64 `json:"lowThreshold,omitempty" tf:"low_threshold,omitempty"`

	// (String) The minimum age for an unused image before it is garbage collected (k8s duration format, eg. 1h)
	// The minimum age for an unused image before it is garbage collected (k8s duration format, eg. 1h)
	MinAge *string `json:"minAge,omitempty" tf:"min_age,omitempty"`
}

type KubeletImageGcParameters struct {

	// (Number) The percent of disk usage after which image garbage collection is always run
	// The percent of disk usage after which image garbage collection is always run
	// +kubebuilder:validation:Optional
	HighThreshold *float64 `json:"highThreshold,omitempty" tf:"high_threshold,omitempty"`

	// (Number) The percent of disk usage before which image garbage collection is never run
	// The percent of disk usage before which image garbage collection is never run
	// +kubebuilder:validation:Optional
	LowThreshold *float64 `json:"lowThreshold,omitempty" tf:"low_threshold,omitempty"`

	// (String) The minimum age for an unused image before it is garbage collected (k8s duration format, eg. 1h)
	// The minimum age for an unused image before it is garbage collected (k8s duration format, eg. 1h)
	// +kubebuilder:validation:Optional
	MinAge *string `json:"minAge,omitempty" tf:"min_age,omitempty"`
}

type SKSNodepoolInitParameters struct {

	// (Set of String) A list of exoscale_anti_affinity_group (IDs) to be attached to the managed instances.
	// A list of [exoscale_anti_affinity_group](./anti_affinity_group.md) (IDs) to be attached to the managed instances.
	// +crossplane:generate:reference:type=github.com/exoscale/provider-exoscale/apis/cluster/compute/v1alpha1.AntiAffinityGroup
	// +listType=set
	AntiAffinityGroupIds []*string `json:"antiAffinityGroupIds,omitempty" tf:"anti_affinity_group_ids,omitempty"`

	// References to AntiAffinityGroup in compute to populate antiAffinityGroupIds.
	// +kubebuilder:validation:Optional
	AntiAffinityGroupIdsRefs []v1.Reference `json:"antiAffinityGroupIdsRefs,omitempty" tf:"-"`

	// Selector for a list of AntiAffinityGroup in compute to populate antiAffinityGroupIds.
	// +kubebuilder:validation:Optional
	AntiAffinityGroupIdsSelector *v1.Selector `json:"antiAffinityGroupIdsSelector,omitempty" tf:"-"`

	// (String) ❗ The parent exoscale_sks_cluster ID.
	// ❗ The parent [exoscale_sks_cluster](./sks_cluster.md) ID.
	// +crossplane:generate:reference:type=github.com/exoscale/provider-exoscale/apis/cluster/compute/v1alpha1.SKSCluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a SKSCluster in compute to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a SKSCluster in compute to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (String) A deploy target ID.
	// A deploy target ID.
	DeployTargetID *string `json:"deployTargetId,omitempty" tf:"deploy_target_id,omitempty"`

	// form text describing the pool.
	// A free-form text describing the pool.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Number) The managed instances disk size (GiB; default: 50).
	// The managed instances disk size (GiB; default: `50`).
	DiskSize *float64 `json:"diskSize,omitempty" tf:"disk_size,omitempty"`

	// (Boolean) Enable IPV6 for the nodepool nodes
	// Enable IPV6 for the nodepool nodes
	IPv6 *bool `json:"ipv6,omitempty" tf:"ipv6,omitempty"`

	// (String) The string used to prefix the managed instances name (default pool).
	// The string used to prefix the managed instances name (default `pool`).
	InstancePrefix *string `json:"instancePrefix,omitempty" tf:"instance_prefix,omitempty"`

	// exo compute instance-type list - for the list of available types).
	// The managed compute instances type (`<family>.<size>`, e.g. `standard.medium`; use the [Exoscale CLI](https://github.com/exoscale/cli/) - `exo compute instance-type list` - for the list of available types).
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// (Block Set) Configuration for this nodepool's kubelet image garbage collector (see below for nested schema)
	// Configuration for this nodepool's kubelet image garbage collector
	KubeletImageGc []KubeletImageGcInitParameters `json:"kubeletImageGc,omitempty" tf:"kubelet_image_gc,omitempty"`

	// (Map of String) A map of key/value labels.
	// A map of key/value labels.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The SKS node pool name.
	// The SKS node pool name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Set of String) A list of exoscale_private_network (IDs) to be attached to the managed instances.
	// A list of [exoscale_private_network](./private_network.md) (IDs) to be attached to the managed instances.
	// +crossplane:generate:reference:type=github.com/exoscale/provider-exoscale/apis/cluster/compute/v1alpha1.PrivateNetwork
	// +listType=set
	PrivateNetworkIds []*string `json:"privateNetworkIds,omitempty" tf:"private_network_ids,omitempty"`

	// References to PrivateNetwork in compute to populate privateNetworkIds.
	// +kubebuilder:validation:Optional
	PrivateNetworkIdsRefs []v1.Reference `json:"privateNetworkIdsRefs,omitempty" tf:"-"`

	// Selector for a list of PrivateNetwork in compute to populate privateNetworkIds.
	// +kubebuilder:validation:Optional
	PrivateNetworkIdsSelector *v1.Selector `json:"privateNetworkIdsSelector,omitempty" tf:"-"`

	// (Set of String) A list of exoscale_security_group (IDs) to be attached to the managed instances.
	// A list of [exoscale_security_group](./security_group.md) (IDs) to be attached to the managed instances.
	// +crossplane:generate:reference:type=github.com/exoscale/provider-exoscale/apis/cluster/compute/v1alpha1.SecurityGroup
	// +listType=set
	SecurityGroupIds []*string `json:"securityGroupIds,omitempty" tf:"security_group_ids,omitempty"`

	// References to SecurityGroup in compute to populate securityGroupIds.
	// +kubebuilder:validation:Optional
	SecurityGroupIdsRefs []v1.Reference `json:"securityGroupIdsRefs,omitempty" tf:"-"`

	// Selector for a list of SecurityGroup in compute to populate securityGroupIds.
	// +kubebuilder:validation:Optional
	SecurityGroupIdsSelector *v1.Selector `json:"securityGroupIdsSelector,omitempty" tf:"-"`

	// (Number)
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`

	// standard partitioning for persistent storage (requires min 100G of disk space) (may only be set at creation time).
	// Create nodes with non-standard partitioning for persistent storage (requires min 100G of disk space) (may only be set at creation time).
	StorageLvm *bool `json:"storageLvm,omitempty" tf:"storage_lvm,omitempty"`

	// (Map of String) A map of key/value Kubernetes taints ('taints = {  = ":" }').
	// A map of key/value Kubernetes [taints](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/) ('taints = { <key> = "<value>:<effect>" }').
	// +mapType=granular
	Taints map[string]*string `json:"taints,omitempty" tf:"taints,omitempty"`

	// (String) ❗ The Exoscale Zone name.
	// ❗ The Exoscale [Zone](https://www.exoscale.com/datacenters/) name.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type SKSNodepoolObservation struct {

	// (Set of String) A list of exoscale_anti_affinity_group (IDs) to be attached to the managed instances.
	// A list of [exoscale_anti_affinity_group](./anti_affinity_group.md) (IDs) to be attached to the managed instances.
	// +listType=set
	AntiAffinityGroupIds []*string `json:"antiAffinityGroupIds,omitempty" tf:"anti_affinity_group_ids,omitempty"`

	// (String) ❗ The parent exoscale_sks_cluster ID.
	// ❗ The parent [exoscale_sks_cluster](./sks_cluster.md) ID.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// (String) The pool creation date.
	// The pool creation date.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) A deploy target ID.
	// A deploy target ID.
	DeployTargetID *string `json:"deployTargetId,omitempty" tf:"deploy_target_id,omitempty"`

	// form text describing the pool.
	// A free-form text describing the pool.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Number) The managed instances disk size (GiB; default: 50).
	// The managed instances disk size (GiB; default: `50`).
	DiskSize *float64 `json:"diskSize,omitempty" tf:"disk_size,omitempty"`

	// (String) The SKS node pool ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Enable IPV6 for the nodepool nodes
	// Enable IPV6 for the nodepool nodes
	IPv6 *bool `json:"ipv6,omitempty" tf:"ipv6,omitempty"`

	// (String) The underlying exoscale_instance_pool ID.
	// The underlying [exoscale_instance_pool](./instance_pool.md) ID.
	InstancePoolID *string `json:"instancePoolId,omitempty" tf:"instance_pool_id,omitempty"`

	// (String) The string used to prefix the managed instances name (default pool).
	// The string used to prefix the managed instances name (default `pool`).
	InstancePrefix *string `json:"instancePrefix,omitempty" tf:"instance_prefix,omitempty"`

	// exo compute instance-type list - for the list of available types).
	// The managed compute instances type (`<family>.<size>`, e.g. `standard.medium`; use the [Exoscale CLI](https://github.com/exoscale/cli/) - `exo compute instance-type list` - for the list of available types).
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// (Block Set) Configuration for this nodepool's kubelet image garbage collector (see below for nested schema)
	// Configuration for this nodepool's kubelet image garbage collector
	KubeletImageGc []KubeletImageGcObservation `json:"kubeletImageGc,omitempty" tf:"kubelet_image_gc,omitempty"`

	// (Map of String) A map of key/value labels.
	// A map of key/value labels.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The SKS node pool name.
	// The SKS node pool name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Set of String) A list of exoscale_private_network (IDs) to be attached to the managed instances.
	// A list of [exoscale_private_network](./private_network.md) (IDs) to be attached to the managed instances.
	// +listType=set
	PrivateNetworkIds []*string `json:"privateNetworkIds,omitempty" tf:"private_network_ids,omitempty"`

	// (Set of String) A list of exoscale_security_group (IDs) to be attached to the managed instances.
	// A list of [exoscale_security_group](./security_group.md) (IDs) to be attached to the managed instances.
	// +listType=set
	SecurityGroupIds []*string `json:"securityGroupIds,omitempty" tf:"security_group_ids,omitempty"`

	// (Number)
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`

	// (String) The current pool state.
	// The current pool state.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// standard partitioning for persistent storage (requires min 100G of disk space) (may only be set at creation time).
	// Create nodes with non-standard partitioning for persistent storage (requires min 100G of disk space) (may only be set at creation time).
	StorageLvm *bool `json:"storageLvm,omitempty" tf:"storage_lvm,omitempty"`

	// (Map of String) A map of key/value Kubernetes taints ('taints = {  = ":" }').
	// A map of key/value Kubernetes [taints](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/) ('taints = { <key> = "<value>:<effect>" }').
	// +mapType=granular
	Taints map[string]*string `json:"taints,omitempty" tf:"taints,omitempty"`

	// (String) The managed instances template ID.
	// The managed instances template ID.
	TemplateID *string `json:"templateId,omitempty" tf:"template_id,omitempty"`

	// (String) The managed instances version.
	// The managed instances version.
	Version *string `json:"version,omitempty" tf:"version,omitempty"`

	// (String) ❗ The Exoscale Zone name.
	// ❗ The Exoscale [Zone](https://www.exoscale.com/datacenters/) name.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type SKSNodepoolParameters struct {

	// (Set of String) A list of exoscale_anti_affinity_group (IDs) to be attached to the managed instances.
	// A list of [exoscale_anti_affinity_group](./anti_affinity_group.md) (IDs) to be attached to the managed instances.
	// +crossplane:generate:reference:type=github.com/exoscale/provider-exoscale/apis/cluster/compute/v1alpha1.AntiAffinityGroup
	// +kubebuilder:validation:Optional
	// +listType=set
	AntiAffinityGroupIds []*string `json:"antiAffinityGroupIds,omitempty" tf:"anti_affinity_group_ids,omitempty"`

	// References to AntiAffinityGroup in compute to populate antiAffinityGroupIds.
	// +kubebuilder:validation:Optional
	AntiAffinityGroupIdsRefs []v1.Reference `json:"antiAffinityGroupIdsRefs,omitempty" tf:"-"`

	// Selector for a list of AntiAffinityGroup in compute to populate antiAffinityGroupIds.
	// +kubebuilder:validation:Optional
	AntiAffinityGroupIdsSelector *v1.Selector `json:"antiAffinityGroupIdsSelector,omitempty" tf:"-"`

	// (String) ❗ The parent exoscale_sks_cluster ID.
	// ❗ The parent [exoscale_sks_cluster](./sks_cluster.md) ID.
	// +crossplane:generate:reference:type=github.com/exoscale/provider-exoscale/apis/cluster/compute/v1alpha1.SKSCluster
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a SKSCluster in compute to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a SKSCluster in compute to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// (String) A deploy target ID.
	// A deploy target ID.
	// +kubebuilder:validation:Optional
	DeployTargetID *string `json:"deployTargetId,omitempty" tf:"deploy_target_id,omitempty"`

	// form text describing the pool.
	// A free-form text describing the pool.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Number) The managed instances disk size (GiB; default: 50).
	// The managed instances disk size (GiB; default: `50`).
	// +kubebuilder:validation:Optional
	DiskSize *float64 `json:"diskSize,omitempty" tf:"disk_size,omitempty"`

	// (Boolean) Enable IPV6 for the nodepool nodes
	// Enable IPV6 for the nodepool nodes
	// +kubebuilder:validation:Optional
	IPv6 *bool `json:"ipv6,omitempty" tf:"ipv6,omitempty"`

	// (String) The string used to prefix the managed instances name (default pool).
	// The string used to prefix the managed instances name (default `pool`).
	// +kubebuilder:validation:Optional
	InstancePrefix *string `json:"instancePrefix,omitempty" tf:"instance_prefix,omitempty"`

	// exo compute instance-type list - for the list of available types).
	// The managed compute instances type (`<family>.<size>`, e.g. `standard.medium`; use the [Exoscale CLI](https://github.com/exoscale/cli/) - `exo compute instance-type list` - for the list of available types).
	// +kubebuilder:validation:Optional
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// (Block Set) Configuration for this nodepool's kubelet image garbage collector (see below for nested schema)
	// Configuration for this nodepool's kubelet image garbage collector
	// +kubebuilder:validation:Optional
	KubeletImageGc []KubeletImageGcParameters `json:"kubeletImageGc,omitempty" tf:"kubelet_image_gc,omitempty"`

	// (Map of String) A map of key/value labels.
	// A map of key/value labels.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The SKS node pool name.
	// The SKS node pool name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Set of String) A list of exoscale_private_network (IDs) to be attached to the managed instances.
	// A list of [exoscale_private_network](./private_network.md) (IDs) to be attached to the managed instances.
	// +crossplane:generate:reference:type=github.com/exoscale/provider-exoscale/apis/cluster/compute/v1alpha1.PrivateNetwork
	// +kubebuilder:validation:Optional
	// +listType=set
	PrivateNetworkIds []*string `json:"privateNetworkIds,omitempty" tf:"private_network_ids,omitempty"`

	// References to PrivateNetwork in compute to populate privateNetworkIds.
	// +kubebuilder:validation:Optional
	PrivateNetworkIdsRefs []v1.Reference `json:"privateNetworkIdsRefs,omitempty" tf:"-"`

	// Selector for a list of PrivateNetwork in compute to populate privateNetworkIds.
	// +kubebuilder:validation:Optional
	PrivateNetworkIdsSelector *v1.Selector `json:"privateNetworkIdsSelector,omitempty" tf:"-"`

	// (Set of String) A list of exoscale_security_group (IDs) to be attached to the managed instances.
	// A list of [exoscale_security_group](./security_group.md) (IDs) to be attached to the managed instances.
	// +crossplane:generate:reference:type=github.com/exoscale/provider-exoscale/apis/cluster/compute/v1alpha1.SecurityGroup
	// +kubebuilder:validation:Optional
	// +listType=set
	SecurityGroupIds []*string `json:"securityGroupIds,omitempty" tf:"security_group_ids,omitempty"`

	// References to SecurityGroup in compute to populate securityGroupIds.
	// +kubebuilder:validation:Optional
	SecurityGroupIdsRefs []v1.Reference `json:"securityGroupIdsRefs,omitempty" tf:"-"`

	// Selector for a list of SecurityGroup in compute to populate securityGroupIds.
	// +kubebuilder:validation:Optional
	SecurityGroupIdsSelector *v1.Selector `json:"securityGroupIdsSelector,omitempty" tf:"-"`

	// (Number)
	// +kubebuilder:validation:Optional
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`

	// standard partitioning for persistent storage (requires min 100G of disk space) (may only be set at creation time).
	// Create nodes with non-standard partitioning for persistent storage (requires min 100G of disk space) (may only be set at creation time).
	// +kubebuilder:validation:Optional
	StorageLvm *bool `json:"storageLvm,omitempty" tf:"storage_lvm,omitempty"`

	// (Map of String) A map of key/value Kubernetes taints ('taints = {  = ":" }').
	// A map of key/value Kubernetes [taints](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/) ('taints = { <key> = "<value>:<effect>" }').
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Taints map[string]*string `json:"taints,omitempty" tf:"taints,omitempty"`

	// (String) ❗ The Exoscale Zone name.
	// ❗ The Exoscale [Zone](https://www.exoscale.com/datacenters/) name.
	// +kubebuilder:validation:Optional
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

// SKSNodepoolSpec defines the desired state of SKSNodepool
type SKSNodepoolSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     SKSNodepoolParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SKSNodepoolInitParameters `json:"initProvider,omitempty"`
}

// SKSNodepoolStatus defines the observed state of SKSNodepool.
type SKSNodepoolStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SKSNodepoolObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SKSNodepool is the Schema for the SKSNodepools API. Manage Exoscale Scalable Kubernetes Service (SKS) Node Pools.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,exoscale}
type SKSNodepool struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.instanceType) || (has(self.initProvider) && has(self.initProvider.instanceType))",message="spec.forProvider.instanceType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.size) || (has(self.initProvider) && has(self.initProvider.size))",message="spec.forProvider.size is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.zone) || (has(self.initProvider) && has(self.initProvider.zone))",message="spec.forProvider.zone is a required parameter"
	Spec   SKSNodepoolSpec   `json:"spec"`
	Status SKSNodepoolStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SKSNodepoolList contains a list of SKSNodepools
type SKSNodepoolList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SKSNodepool `json:"items"`
}

// Repository type metadata.
var (
	SKSNodepool_Kind             = "SKSNodepool"
	SKSNodepool_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SKSNodepool_Kind}.String()
	SKSNodepool_KindAPIVersion   = SKSNodepool_Kind + "." + CRDGroupVersion.String()
	SKSNodepool_GroupVersionKind = CRDGroupVersion.WithKind(SKSNodepool_Kind)
)

func init() {
	SchemeBuilder.Register(&SKSNodepool{}, &SKSNodepoolList{})
}
